gate cu1_4960027712(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
}
gate cu1_4960037984(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960037456(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960035632(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960469360(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960469216(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960469408(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960469456(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960469312(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960469600(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960469792(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960469840(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960469696(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960470272(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960470560(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960470752(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960470368(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960470608(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960470512(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960470944(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960471136(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960471040(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960470896(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960471328(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960471520(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960470176(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960470032(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960471712(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960471808(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960471856(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960299600(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960300224(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960299552(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960299696(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960472000(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960471904(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960472336(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960472528(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960472432(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960472288(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960472720(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960472912(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960471568(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960471424(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960473104(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960473200(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960473248(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960472768(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960473440(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960472864(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960473584(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960473632(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960473488(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960473776(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960473968(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960474016(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960473872(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960473008(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960472672(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960474448(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960474736(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960474928(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960474544(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960474784(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960474688(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960475120(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960475312(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960475216(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960475072(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960475504(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960475696(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960474352(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960474208(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960475888(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960475984(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960476032(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960475552(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960476224(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960475648(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960476368(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960476416(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960476272(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960476560(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960476752(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960476800(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960476656(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960475792(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960475456(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960477232(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960477520(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960477712(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960477328(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960477568(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960477472(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960477904(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960478096(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960478000(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960477856(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960478288(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960478480(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960477136(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960476992(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960478672(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960478768(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960478816(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960478336(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960479008(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960478432(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960479152(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960479200(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960479056(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960479344(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960479536(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960479584(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960479440(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960478576(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960478240(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960480016(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960480304(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960480496(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960480112(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960480352(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960480256(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960480688(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960480880(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960480784(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960480640(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960481072(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960481264(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960479920(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960479776(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960481456(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960481552(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960481600(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960481120(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960481792(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960481216(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960481936(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960481984(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960481840(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960482128(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960482320(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960482368(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960482224(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960481360(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960481024(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960482800(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960483088(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960483280(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960482896(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960483136(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960483040(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960483472(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960483664(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960483568(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960483424(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960483856(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960484048(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960482704(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960482560(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960484240(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960484336(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960484384(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960483904(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960484576(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960484000(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960484720(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960484768(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960484624(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960484912(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960485104(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960485152(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960484096(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960483952(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960485296(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960485200(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960469168(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960698592(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960698688(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960698784(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960698880(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960698976(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960699072(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960699168(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960699264(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960699360(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960699456(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960699552(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960699648(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960699744(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960699840(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960699936(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960700032(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960700128(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960700224(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960700320(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960700416(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960700512(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960700608(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960700704(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960700800(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960700896(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960700992(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960701088(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960701184(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960701280(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960701376(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960701472(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960701568(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960701664(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960701760(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960701856(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960701952(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960702048(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960702144(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960702240(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960702336(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960702432(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960702528(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960702624(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960702720(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960702816(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960702912(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960703008(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960703104(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960703200(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960703296(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960703392(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960703488(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960703584(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960703680(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960703776(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960703872(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960703968(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960704064(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960704160(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960704256(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960704352(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960704448(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960704544(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960704640(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960704736(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960704832(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960704928(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960705024(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960705120(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960705216(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960705312(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960705408(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960705504(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960705600(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960705696(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960705792(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960705888(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960705984(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate cu1_4960706080(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/512) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/512) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/512) _gate_q_1;
}
gate mcu1_4960305120(_gate_p_0) _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8, _gate_q_9 {
  cu1_4960027712(pi/256) _gate_q_8, _gate_q_9;
  cx _gate_q_8, _gate_q_7;
  cu1_4960037984(-pi/256) _gate_q_7, _gate_q_9;
  cx _gate_q_8, _gate_q_7;
  cu1_4960027712(pi/256) _gate_q_7, _gate_q_9;
  cx _gate_q_7, _gate_q_6;
  cu1_4960037456(-pi/256) _gate_q_6, _gate_q_9;
  cx _gate_q_8, _gate_q_6;
  cu1_4960027712(pi/256) _gate_q_6, _gate_q_9;
  cx _gate_q_7, _gate_q_6;
  cu1_4960035632(-pi/256) _gate_q_6, _gate_q_9;
  cx _gate_q_8, _gate_q_6;
  cu1_4960027712(pi/256) _gate_q_6, _gate_q_9;
  cx _gate_q_6, _gate_q_5;
  cu1_4960469360(-pi/256) _gate_q_5, _gate_q_9;
  cx _gate_q_8, _gate_q_5;
  cu1_4960027712(pi/256) _gate_q_5, _gate_q_9;
  cx _gate_q_7, _gate_q_5;
  cu1_4960469216(-pi/256) _gate_q_5, _gate_q_9;
  cx _gate_q_8, _gate_q_5;
  cu1_4960027712(pi/256) _gate_q_5, _gate_q_9;
  cx _gate_q_6, _gate_q_5;
  cu1_4960469408(-pi/256) _gate_q_5, _gate_q_9;
  cx _gate_q_8, _gate_q_5;
  cu1_4960027712(pi/256) _gate_q_5, _gate_q_9;
  cx _gate_q_7, _gate_q_5;
  cu1_4960469456(-pi/256) _gate_q_5, _gate_q_9;
  cx _gate_q_8, _gate_q_5;
  cu1_4960027712(pi/256) _gate_q_5, _gate_q_9;
  cx _gate_q_5, _gate_q_4;
  cu1_4960469312(-pi/256) _gate_q_4, _gate_q_9;
  cx _gate_q_8, _gate_q_4;
  cu1_4960027712(pi/256) _gate_q_4, _gate_q_9;
  cx _gate_q_7, _gate_q_4;
  cu1_4960469600(-pi/256) _gate_q_4, _gate_q_9;
  cx _gate_q_8, _gate_q_4;
  cu1_4960027712(pi/256) _gate_q_4, _gate_q_9;
  cx _gate_q_6, _gate_q_4;
  cu1_4960469792(-pi/256) _gate_q_4, _gate_q_9;
  cx _gate_q_8, _gate_q_4;
  cu1_4960027712(pi/256) _gate_q_4, _gate_q_9;
  cx _gate_q_7, _gate_q_4;
  cu1_4960469840(-pi/256) _gate_q_4, _gate_q_9;
  cx _gate_q_8, _gate_q_4;
  cu1_4960027712(pi/256) _gate_q_4, _gate_q_9;
  cx _gate_q_5, _gate_q_4;
  cu1_4960469696(-pi/256) _gate_q_4, _gate_q_9;
  cx _gate_q_8, _gate_q_4;
  cu1_4960027712(pi/256) _gate_q_4, _gate_q_9;
  cx _gate_q_7, _gate_q_4;
  cu1_4960470272(-pi/256) _gate_q_4, _gate_q_9;
  cx _gate_q_8, _gate_q_4;
  cu1_4960027712(pi/256) _gate_q_4, _gate_q_9;
  cx _gate_q_6, _gate_q_4;
  cu1_4960470560(-pi/256) _gate_q_4, _gate_q_9;
  cx _gate_q_8, _gate_q_4;
  cu1_4960027712(pi/256) _gate_q_4, _gate_q_9;
  cx _gate_q_7, _gate_q_4;
  cu1_4960470752(-pi/256) _gate_q_4, _gate_q_9;
  cx _gate_q_8, _gate_q_4;
  cu1_4960027712(pi/256) _gate_q_4, _gate_q_9;
  cx _gate_q_4, _gate_q_3;
  cu1_4960470368(-pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_8, _gate_q_3;
  cu1_4960027712(pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_7, _gate_q_3;
  cu1_4960470608(-pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_8, _gate_q_3;
  cu1_4960027712(pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_6, _gate_q_3;
  cu1_4960470512(-pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_8, _gate_q_3;
  cu1_4960027712(pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_7, _gate_q_3;
  cu1_4960470944(-pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_8, _gate_q_3;
  cu1_4960027712(pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_5, _gate_q_3;
  cu1_4960471136(-pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_8, _gate_q_3;
  cu1_4960027712(pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_7, _gate_q_3;
  cu1_4960471040(-pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_8, _gate_q_3;
  cu1_4960027712(pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_6, _gate_q_3;
  cu1_4960470896(-pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_8, _gate_q_3;
  cu1_4960027712(pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_7, _gate_q_3;
  cu1_4960471328(-pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_8, _gate_q_3;
  cu1_4960027712(pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_4, _gate_q_3;
  cu1_4960471520(-pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_8, _gate_q_3;
  cu1_4960027712(pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_7, _gate_q_3;
  cu1_4960470176(-pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_8, _gate_q_3;
  cu1_4960027712(pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_6, _gate_q_3;
  cu1_4960470032(-pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_8, _gate_q_3;
  cu1_4960027712(pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_7, _gate_q_3;
  cu1_4960471712(-pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_8, _gate_q_3;
  cu1_4960027712(pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_5, _gate_q_3;
  cu1_4960471808(-pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_8, _gate_q_3;
  cu1_4960027712(pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_7, _gate_q_3;
  cu1_4960471856(-pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_8, _gate_q_3;
  cu1_4960027712(pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_6, _gate_q_3;
  cu1_4960299600(-pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_8, _gate_q_3;
  cu1_4960027712(pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_7, _gate_q_3;
  cu1_4960300224(-pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_8, _gate_q_3;
  cu1_4960027712(pi/256) _gate_q_3, _gate_q_9;
  cx _gate_q_3, _gate_q_2;
  cu1_4960299552(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_7, _gate_q_2;
  cu1_4960299696(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_6, _gate_q_2;
  cu1_4960472000(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_7, _gate_q_2;
  cu1_4960471904(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_5, _gate_q_2;
  cu1_4960472336(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_7, _gate_q_2;
  cu1_4960472528(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_6, _gate_q_2;
  cu1_4960472432(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_7, _gate_q_2;
  cu1_4960472288(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_4, _gate_q_2;
  cu1_4960472720(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_7, _gate_q_2;
  cu1_4960472912(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_6, _gate_q_2;
  cu1_4960471568(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_7, _gate_q_2;
  cu1_4960471424(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_5, _gate_q_2;
  cu1_4960473104(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_7, _gate_q_2;
  cu1_4960473200(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_6, _gate_q_2;
  cu1_4960473248(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_7, _gate_q_2;
  cu1_4960472768(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_3, _gate_q_2;
  cu1_4960473440(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_7, _gate_q_2;
  cu1_4960472864(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_6, _gate_q_2;
  cu1_4960473584(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_7, _gate_q_2;
  cu1_4960473632(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_5, _gate_q_2;
  cu1_4960473488(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_7, _gate_q_2;
  cu1_4960473776(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_6, _gate_q_2;
  cu1_4960473968(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_7, _gate_q_2;
  cu1_4960474016(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_4, _gate_q_2;
  cu1_4960473872(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_7, _gate_q_2;
  cu1_4960473008(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_6, _gate_q_2;
  cu1_4960472672(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_7, _gate_q_2;
  cu1_4960474448(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_5, _gate_q_2;
  cu1_4960474736(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_7, _gate_q_2;
  cu1_4960474928(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_6, _gate_q_2;
  cu1_4960474544(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_7, _gate_q_2;
  cu1_4960474784(-pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_8, _gate_q_2;
  cu1_4960027712(pi/256) _gate_q_2, _gate_q_9;
  cx _gate_q_2, _gate_q_1;
  cu1_4960474688(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960475120(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_6, _gate_q_1;
  cu1_4960475312(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960475216(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_5, _gate_q_1;
  cu1_4960475072(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960475504(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_6, _gate_q_1;
  cu1_4960475696(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960474352(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_4, _gate_q_1;
  cu1_4960474208(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960475888(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_6, _gate_q_1;
  cu1_4960475984(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960476032(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_5, _gate_q_1;
  cu1_4960475552(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960476224(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_6, _gate_q_1;
  cu1_4960475648(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960476368(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_3, _gate_q_1;
  cu1_4960476416(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960476272(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_6, _gate_q_1;
  cu1_4960476560(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960476752(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_5, _gate_q_1;
  cu1_4960476800(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960476656(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_6, _gate_q_1;
  cu1_4960475792(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960475456(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_4, _gate_q_1;
  cu1_4960477232(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960477520(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_6, _gate_q_1;
  cu1_4960477712(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960477328(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_5, _gate_q_1;
  cu1_4960477568(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960477472(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_6, _gate_q_1;
  cu1_4960477904(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960478096(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_2, _gate_q_1;
  cu1_4960478000(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960477856(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_6, _gate_q_1;
  cu1_4960478288(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960478480(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_5, _gate_q_1;
  cu1_4960477136(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960476992(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_6, _gate_q_1;
  cu1_4960478672(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960478768(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_4, _gate_q_1;
  cu1_4960478816(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960478336(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_6, _gate_q_1;
  cu1_4960479008(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960478432(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_5, _gate_q_1;
  cu1_4960479152(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960479200(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_6, _gate_q_1;
  cu1_4960479056(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960479344(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_3, _gate_q_1;
  cu1_4960479536(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960479584(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_6, _gate_q_1;
  cu1_4960479440(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960478576(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_5, _gate_q_1;
  cu1_4960478240(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960480016(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_6, _gate_q_1;
  cu1_4960480304(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960480496(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_4, _gate_q_1;
  cu1_4960480112(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960480352(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_6, _gate_q_1;
  cu1_4960480256(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960480688(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_5, _gate_q_1;
  cu1_4960480880(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960480784(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_6, _gate_q_1;
  cu1_4960480640(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_7, _gate_q_1;
  cu1_4960481072(-pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_8, _gate_q_1;
  cu1_4960027712(pi/256) _gate_q_1, _gate_q_9;
  cx _gate_q_1, _gate_q_0;
  cu1_4960481264(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960479920(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960479776(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960481456(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_5, _gate_q_0;
  cu1_4960481552(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960481600(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960481120(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960481792(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_4, _gate_q_0;
  cu1_4960481216(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960481936(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960481984(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960481840(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_5, _gate_q_0;
  cu1_4960482128(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960482320(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960482368(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960482224(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_3, _gate_q_0;
  cu1_4960481360(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960481024(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960482800(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960483088(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_5, _gate_q_0;
  cu1_4960483280(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960482896(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960483136(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960483040(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_4, _gate_q_0;
  cu1_4960483472(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960483664(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960483568(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960483424(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_5, _gate_q_0;
  cu1_4960483856(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960484048(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960482704(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960482560(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_2, _gate_q_0;
  cu1_4960484240(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960484336(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960484384(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960483904(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_5, _gate_q_0;
  cu1_4960484576(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960484000(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960484720(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960484768(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_4, _gate_q_0;
  cu1_4960484624(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960484912(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960485104(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960485152(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_5, _gate_q_0;
  cu1_4960484096(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960483952(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960485296(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960485200(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_3, _gate_q_0;
  cu1_4960469168(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960698592(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960698688(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960698784(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_5, _gate_q_0;
  cu1_4960698880(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960698976(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960699072(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960699168(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_4, _gate_q_0;
  cu1_4960699264(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960699360(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960699456(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960699552(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_5, _gate_q_0;
  cu1_4960699648(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960699744(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960699840(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960699936(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_1, _gate_q_0;
  cu1_4960700032(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960700128(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960700224(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960700320(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_5, _gate_q_0;
  cu1_4960700416(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960700512(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960700608(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960700704(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_4, _gate_q_0;
  cu1_4960700800(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960700896(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960700992(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960701088(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_5, _gate_q_0;
  cu1_4960701184(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960701280(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960701376(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960701472(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_3, _gate_q_0;
  cu1_4960701568(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960701664(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960701760(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960701856(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_5, _gate_q_0;
  cu1_4960701952(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960702048(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960702144(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960702240(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_4, _gate_q_0;
  cu1_4960702336(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960702432(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960702528(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960702624(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_5, _gate_q_0;
  cu1_4960702720(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960702816(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960702912(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960703008(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_2, _gate_q_0;
  cu1_4960703104(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960703200(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960703296(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960703392(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_5, _gate_q_0;
  cu1_4960703488(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960703584(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960703680(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960703776(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_4, _gate_q_0;
  cu1_4960703872(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960703968(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960704064(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960704160(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_5, _gate_q_0;
  cu1_4960704256(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960704352(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960704448(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960704544(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_3, _gate_q_0;
  cu1_4960704640(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960704736(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960704832(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960704928(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_5, _gate_q_0;
  cu1_4960705024(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960705120(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960705216(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960705312(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_4, _gate_q_0;
  cu1_4960705408(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960705504(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960705600(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960705696(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_5, _gate_q_0;
  cu1_4960705792(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960705888(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_6, _gate_q_0;
  cu1_4960705984(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_7, _gate_q_0;
  cu1_4960706080(-pi/256) _gate_q_0, _gate_q_9;
  cx _gate_q_8, _gate_q_0;
  cu1_4960027712(pi/256) _gate_q_0, _gate_q_9;
}
gate mcx _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8, _gate_q_9 {
  h _gate_q_9;
  mcu1_4960305120(pi) _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8, _gate_q_9;
  h _gate_q_9;
}