gate mcphase_5895301760(_gate_p_0) _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7 {
  cp(pi/128) _gate_q_6, _gate_q_7;
  cx _gate_q_6, _gate_q_5;
  cp(-pi/128) _gate_q_5, _gate_q_7;
  cx _gate_q_6, _gate_q_5;
  cp(pi/128) _gate_q_5, _gate_q_7;
  cx _gate_q_5, _gate_q_4;
  cp(-pi/128) _gate_q_4, _gate_q_7;
  cx _gate_q_6, _gate_q_4;
  cp(pi/128) _gate_q_4, _gate_q_7;
  cx _gate_q_5, _gate_q_4;
  cp(-pi/128) _gate_q_4, _gate_q_7;
  cx _gate_q_6, _gate_q_4;
  cp(pi/128) _gate_q_4, _gate_q_7;
  cx _gate_q_4, _gate_q_3;
  cp(-pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_6, _gate_q_3;
  cp(pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_5, _gate_q_3;
  cp(-pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_6, _gate_q_3;
  cp(pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_4, _gate_q_3;
  cp(-pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_6, _gate_q_3;
  cp(pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_5, _gate_q_3;
  cp(-pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_6, _gate_q_3;
  cp(pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_3, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_5, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_4, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_5, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_3, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_5, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_4, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_5, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_2, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_4, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_3, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_4, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_2, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_4, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_3, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_4, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_1, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_3, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_2, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_3, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_1, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_3, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_2, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_3, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
}
gate c8z _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8 {
  U(pi/2, 0, pi) _gate_q_8;
  cx _gate_q_8, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_8, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  U(pi/2, pi/4, -3*pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  p(-pi/4) _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  p(pi/4) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  U(pi/2, 0, 3*pi/4) _gate_q_4;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, -pi/4, 3*pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_8, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_8, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  p(-pi/4) _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  p(pi/4) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  U(pi/2, 0, 3*pi/4) _gate_q_4;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, 0, 3*pi/4) _gate_q_5;
  U(pi/4, pi/2, -pi/2) _gate_q_8;
  cx _gate_q_8, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_8, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  U(pi/2, pi/4, -3*pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_2;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_3;
  cx _gate_q_5, _gate_q_2;
  p(-pi/4) _gate_q_2;
  cx _gate_q_4, _gate_q_2;
  p(pi/4) _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  U(pi/2, 0, 3*pi/4) _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, -pi/4, 3*pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_8, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_8, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_2;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_3;
  cx _gate_q_5, _gate_q_2;
  p(-pi/4) _gate_q_2;
  cx _gate_q_4, _gate_q_2;
  p(pi/4) _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  U(pi/2, 0, 3*pi/4) _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, 0, 3*pi/4) _gate_q_3;
  U(pi/4, -pi/2, pi/2) _gate_q_8;
  cx _gate_q_8, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_8, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  U(pi/2, pi/4, -3*pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  p(-pi/4) _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  p(pi/4) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  U(pi/2, 0, 3*pi/4) _gate_q_4;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, -pi/4, 3*pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_8, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_8, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  p(-pi/4) _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  p(pi/4) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  U(pi/2, 0, 3*pi/4) _gate_q_4;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, 0, 3*pi/4) _gate_q_5;
  U(pi/4, pi/2, -pi/2) _gate_q_8;
  cx _gate_q_8, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_8, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  U(pi/2, pi/4, -3*pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_2;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_3;
  cx _gate_q_5, _gate_q_2;
  p(-pi/4) _gate_q_2;
  cx _gate_q_4, _gate_q_2;
  p(pi/4) _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  U(pi/2, 0, 3*pi/4) _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, -pi/4, 3*pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_8, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_8, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_2;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_3;
  cx _gate_q_5, _gate_q_2;
  p(-pi/4) _gate_q_2;
  cx _gate_q_4, _gate_q_2;
  p(pi/4) _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  U(pi/2, 0, 3*pi/4) _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, 0, 3*pi/4) _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_8;
  mcphase_5895301760(pi/2) _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7;
}
gate Oracle _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8 {
  x _gate_q_4;
  x _gate_q_8;
  c8z _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8;
  x _gate_q_4;
  x _gate_q_8;
}
gate cu1_5368046912(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
}
gate cu1_5368050704(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368051760(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368050608(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368050224(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368044992(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368049600(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368041392(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368049840(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368042784(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368046048(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368046096(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368037936(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368047392(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368038560(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368049408(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368048304(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368038896(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368040912(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368043024(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368121104(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368125952(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368128544(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368122640(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368124848(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368134976(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368128208(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368120768(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368132624(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368132912(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368135456(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368133584(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368122880(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368127680(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368128352(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368131568(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368133056(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368122064(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368127728(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368120624(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368123216(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368119664(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368131904(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368128880(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368129600(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368119712(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368130464(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368126144(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368127488(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368125568(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368124080(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368128688(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368129168(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368126048(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368122784(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368130992(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368131952(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368123360(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368132576(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368130128(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895246368(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895250400(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895251360(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895251312(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895255584(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895253184(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895253232(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895253376(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895253616(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895243872(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895246464(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895244640(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895243296(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895244784(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895245408(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895245936(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895245312(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895256112(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895256304(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895254048(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895244832(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895249248(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895244304(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895250160(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895248720(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895248432(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895254480(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895258032(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895247424(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895244256(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895242672(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895245264(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895248576(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895254336(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895254288(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895254672(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895248240(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895253952(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895255008(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895245504(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368522912(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368522624(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368526704(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368522528(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368526512(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368514320(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368526224(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368522000(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368517152(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368522336(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368528384(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368516192(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368528480(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368518352(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368518736(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368515616(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368516048(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368514128(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368519648(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368516336(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368517200(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368516144(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368516288(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368522672(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368526368(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368522576(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368517344(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368516576(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate mcu1_5368049360(_gate_p_0) _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8 {
  cu1_5368046912(pi/128) _gate_q_7, _gate_q_8;
  cx _gate_q_7, _gate_q_6;
  cu1_5368050704(-pi/128) _gate_q_6, _gate_q_8;
  cx _gate_q_7, _gate_q_6;
  cu1_5368046912(pi/128) _gate_q_6, _gate_q_8;
  cx _gate_q_6, _gate_q_5;
  cu1_5368051760(-pi/128) _gate_q_5, _gate_q_8;
  cx _gate_q_7, _gate_q_5;
  cu1_5368046912(pi/128) _gate_q_5, _gate_q_8;
  cx _gate_q_6, _gate_q_5;
  cu1_5368050608(-pi/128) _gate_q_5, _gate_q_8;
  cx _gate_q_7, _gate_q_5;
  cu1_5368046912(pi/128) _gate_q_5, _gate_q_8;
  cx _gate_q_5, _gate_q_4;
  cu1_5368050224(-pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_7, _gate_q_4;
  cu1_5368046912(pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_6, _gate_q_4;
  cu1_5368044992(-pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_7, _gate_q_4;
  cu1_5368046912(pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_5, _gate_q_4;
  cu1_5368049600(-pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_7, _gate_q_4;
  cu1_5368046912(pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_6, _gate_q_4;
  cu1_5368041392(-pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_7, _gate_q_4;
  cu1_5368046912(pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_4, _gate_q_3;
  cu1_5368049840(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5368046912(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_6, _gate_q_3;
  cu1_5368042784(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5368046912(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_5, _gate_q_3;
  cu1_5368046048(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5368046912(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_6, _gate_q_3;
  cu1_5368046096(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5368046912(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_4, _gate_q_3;
  cu1_5368037936(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5368046912(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_6, _gate_q_3;
  cu1_5368047392(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5368046912(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_5, _gate_q_3;
  cu1_5368038560(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5368046912(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_6, _gate_q_3;
  cu1_5368049408(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5368046912(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_3, _gate_q_2;
  cu1_5368048304(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368046912(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5368038896(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368046912(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_5, _gate_q_2;
  cu1_5368040912(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368046912(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5368043024(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368046912(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_4, _gate_q_2;
  cu1_5368121104(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368046912(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5368125952(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368046912(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_5, _gate_q_2;
  cu1_5368128544(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368046912(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5368122640(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368046912(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_3, _gate_q_2;
  cu1_5368124848(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368046912(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5368134976(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368046912(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_5, _gate_q_2;
  cu1_5368128208(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368046912(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5368120768(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368046912(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_4, _gate_q_2;
  cu1_5368132624(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368046912(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5368132912(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368046912(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_5, _gate_q_2;
  cu1_5368135456(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368046912(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5368133584(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368046912(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_2, _gate_q_1;
  cu1_5368122880(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5368127680(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5368128352(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5368131568(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_4, _gate_q_1;
  cu1_5368133056(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5368122064(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5368127728(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5368120624(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_3, _gate_q_1;
  cu1_5368123216(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5368119664(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5368131904(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5368128880(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_4, _gate_q_1;
  cu1_5368129600(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5368119712(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5368130464(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5368126144(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_2, _gate_q_1;
  cu1_5368127488(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5368125568(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5368124080(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5368128688(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_4, _gate_q_1;
  cu1_5368129168(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5368126048(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5368122784(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5368130992(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_3, _gate_q_1;
  cu1_5368131952(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5368123360(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5368132576(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5368130128(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_4, _gate_q_1;
  cu1_5895246368(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895250400(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5895251360(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895251312(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368046912(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_1, _gate_q_0;
  cu1_5895255584(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895253184(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5895253232(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895253376(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5895253616(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895243872(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5895246464(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895244640(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_3, _gate_q_0;
  cu1_5895243296(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895244784(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5895245408(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895245936(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5895245312(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895256112(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5895256304(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895254048(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_2, _gate_q_0;
  cu1_5895244832(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895249248(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5895244304(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895250160(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5895248720(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895248432(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5895254480(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895258032(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_3, _gate_q_0;
  cu1_5895247424(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895244256(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5895242672(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895245264(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5895248576(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895254336(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5895254288(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895254672(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_1, _gate_q_0;
  cu1_5895248240(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895253952(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5895255008(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895245504(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5368522912(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368522624(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5368526704(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368522528(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_3, _gate_q_0;
  cu1_5368526512(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368514320(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5368526224(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368522000(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5368517152(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368522336(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5368528384(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368516192(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_2, _gate_q_0;
  cu1_5368528480(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368518352(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5368518736(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368515616(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5368516048(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368514128(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5368519648(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368516336(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_3, _gate_q_0;
  cu1_5368517200(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368516144(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5368516288(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368522672(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5368526368(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368522576(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5368517344(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368516576(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368046912(pi/128) _gate_q_0, _gate_q_8;
}
gate mcx _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8 {
  h _gate_q_8;
  mcu1_5368049360(pi) _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8;
  h _gate_q_8;
}