import cirq

def diffuser_circuit():
    qubits = cirq.LineQubit.range(5)
    circuit = cirq.Circuit()
    circuit.append(cirq.H(qubits[0]))
    circuit.append(cirq.H(qubits[1]))
    circuit.append(cirq.H(qubits[2]))
    circuit.append(cirq.H(qubits[3]))
    circuit.append(cirq.H(qubits[4]))
    circuit.append(cirq.X(qubits[0]))
    circuit.append(cirq.X(qubits[1]))
    circuit.append(cirq.X(qubits[2]))
    circuit.append(cirq.X(qubits[3]))
    circuit.append(cirq.X(qubits[4]))
    circuit.append(cirq.H(qubits[4]))
    circuit.append(cirq.X.controlled(num_controls=4).on(*qubits))
    circuit.append(cirq.H(qubits[4]))
    circuit.append(cirq.X(qubits[0]))
    circuit.append(cirq.X(qubits[1]))
    circuit.append(cirq.X(qubits[2]))
    circuit.append(cirq.X(qubits[3]))
    circuit.append(cirq.X(qubits[4]))
    circuit.append(cirq.H(qubits[0]))
    circuit.append(cirq.H(qubits[1]))
    circuit.append(cirq.H(qubits[2]))
    circuit.append(cirq.H(qubits[3]))
    circuit.append(cirq.H(qubits[4]))
    return circuit
