import cirq

def diffuser_circuit():
    qubits = cirq.LineQubit.range(11)
    circuit = cirq.Circuit()
    circuit.append(cirq.H(qubits[0]))
    circuit.append(cirq.H(qubits[1]))
    circuit.append(cirq.H(qubits[2]))
    circuit.append(cirq.H(qubits[3]))
    circuit.append(cirq.H(qubits[4]))
    circuit.append(cirq.H(qubits[5]))
    circuit.append(cirq.H(qubits[6]))
    circuit.append(cirq.H(qubits[7]))
    circuit.append(cirq.H(qubits[8]))
    circuit.append(cirq.H(qubits[9]))
    circuit.append(cirq.H(qubits[10]))
    circuit.append(cirq.X(qubits[0]))
    circuit.append(cirq.X(qubits[1]))
    circuit.append(cirq.X(qubits[2]))
    circuit.append(cirq.X(qubits[3]))
    circuit.append(cirq.X(qubits[4]))
    circuit.append(cirq.X(qubits[5]))
    circuit.append(cirq.X(qubits[6]))
    circuit.append(cirq.X(qubits[7]))
    circuit.append(cirq.X(qubits[8]))
    circuit.append(cirq.X(qubits[9]))
    circuit.append(cirq.X(qubits[10]))
    circuit.append(cirq.H(qubits[10]))
    circuit.append(cirq.X.controlled(num_controls=10).on(*qubits))
    circuit.append(cirq.H(qubits[10]))
    circuit.append(cirq.X(qubits[0]))
    circuit.append(cirq.X(qubits[1]))
    circuit.append(cirq.X(qubits[2]))
    circuit.append(cirq.X(qubits[3]))
    circuit.append(cirq.X(qubits[4]))
    circuit.append(cirq.X(qubits[5]))
    circuit.append(cirq.X(qubits[6]))
    circuit.append(cirq.X(qubits[7]))
    circuit.append(cirq.X(qubits[8]))
    circuit.append(cirq.X(qubits[9]))
    circuit.append(cirq.X(qubits[10]))
    circuit.append(cirq.H(qubits[0]))
    circuit.append(cirq.H(qubits[1]))
    circuit.append(cirq.H(qubits[2]))
    circuit.append(cirq.H(qubits[3]))
    circuit.append(cirq.H(qubits[4]))
    circuit.append(cirq.H(qubits[5]))
    circuit.append(cirq.H(qubits[6]))
    circuit.append(cirq.H(qubits[7]))
    circuit.append(cirq.H(qubits[8]))
    circuit.append(cirq.H(qubits[9]))
    circuit.append(cirq.H(qubits[10]))
    return circuit
