gate mcphase_5368525984(_gate_p_0) _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7 {
  cp(pi/128) _gate_q_6, _gate_q_7;
  cx _gate_q_6, _gate_q_5;
  cp(-pi/128) _gate_q_5, _gate_q_7;
  cx _gate_q_6, _gate_q_5;
  cp(pi/128) _gate_q_5, _gate_q_7;
  cx _gate_q_5, _gate_q_4;
  cp(-pi/128) _gate_q_4, _gate_q_7;
  cx _gate_q_6, _gate_q_4;
  cp(pi/128) _gate_q_4, _gate_q_7;
  cx _gate_q_5, _gate_q_4;
  cp(-pi/128) _gate_q_4, _gate_q_7;
  cx _gate_q_6, _gate_q_4;
  cp(pi/128) _gate_q_4, _gate_q_7;
  cx _gate_q_4, _gate_q_3;
  cp(-pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_6, _gate_q_3;
  cp(pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_5, _gate_q_3;
  cp(-pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_6, _gate_q_3;
  cp(pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_4, _gate_q_3;
  cp(-pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_6, _gate_q_3;
  cp(pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_5, _gate_q_3;
  cp(-pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_6, _gate_q_3;
  cp(pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_3, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_5, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_4, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_5, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_3, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_5, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_4, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_5, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_2, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_4, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_3, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_4, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_2, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_4, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_3, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_4, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_1, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_3, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_2, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_3, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_1, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_3, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_2, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_3, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
}
gate c8z _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8 {
  U(pi/2, 0, pi) _gate_q_8;
  cx _gate_q_8, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_8, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  U(pi/2, pi/4, -3*pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  p(-pi/4) _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  p(pi/4) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  U(pi/2, 0, 3*pi/4) _gate_q_4;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, -pi/4, 3*pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_8, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_8, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  p(-pi/4) _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  p(pi/4) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  U(pi/2, 0, 3*pi/4) _gate_q_4;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, 0, 3*pi/4) _gate_q_5;
  U(pi/4, pi/2, -pi/2) _gate_q_8;
  cx _gate_q_8, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_8, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  U(pi/2, pi/4, -3*pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_2;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_3;
  cx _gate_q_5, _gate_q_2;
  p(-pi/4) _gate_q_2;
  cx _gate_q_4, _gate_q_2;
  p(pi/4) _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  U(pi/2, 0, 3*pi/4) _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, -pi/4, 3*pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_8, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_8, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_2;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_3;
  cx _gate_q_5, _gate_q_2;
  p(-pi/4) _gate_q_2;
  cx _gate_q_4, _gate_q_2;
  p(pi/4) _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  U(pi/2, 0, 3*pi/4) _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, 0, 3*pi/4) _gate_q_3;
  U(pi/4, -pi/2, pi/2) _gate_q_8;
  cx _gate_q_8, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_8, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  U(pi/2, pi/4, -3*pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  p(-pi/4) _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  p(pi/4) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  U(pi/2, 0, 3*pi/4) _gate_q_4;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, -pi/4, 3*pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_8, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_8, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  p(-pi/4) _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  p(pi/4) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  U(pi/2, 0, 3*pi/4) _gate_q_4;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, 0, 3*pi/4) _gate_q_5;
  U(pi/4, pi/2, -pi/2) _gate_q_8;
  cx _gate_q_8, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_8, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  U(pi/2, pi/4, -3*pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_2;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_3;
  cx _gate_q_5, _gate_q_2;
  p(-pi/4) _gate_q_2;
  cx _gate_q_4, _gate_q_2;
  p(pi/4) _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  U(pi/2, 0, 3*pi/4) _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, -pi/4, 3*pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_8, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_8, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_2;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_3;
  cx _gate_q_5, _gate_q_2;
  p(-pi/4) _gate_q_2;
  cx _gate_q_4, _gate_q_2;
  p(pi/4) _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  U(pi/2, 0, 3*pi/4) _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, 0, 3*pi/4) _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_8;
  mcphase_5368525984(pi/2) _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7;
}
gate Oracle _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8 {
  x _gate_q_1;
  x _gate_q_4;
  x _gate_q_5;
  x _gate_q_6;
  x _gate_q_8;
  c8z _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8;
  x _gate_q_1;
  x _gate_q_4;
  x _gate_q_5;
  x _gate_q_6;
  x _gate_q_8;
}
gate cu1_5368516240(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
}
gate cu1_5368519984(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368523248(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368526032(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368522144(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368527568(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368523968(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368520272(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368520128(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368523488(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368524496(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368517776(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368515376(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368514272(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368526416(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368527088(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368524448(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368518880(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368513264(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368526080(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368517920(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368516816(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368513072(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368524928(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368515040(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368525264(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368516384(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368515088(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368521712(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368513840(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368512976(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368519408(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368518304(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368525072(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368513216(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368522816(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368514080(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368515472(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368527664(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368521904(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368519072(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368520032(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368517488(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368516480(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368527616(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368519888(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368528192(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368527808(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368519840(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368521808(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368525168(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368520992(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368523104(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368518832(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364083760(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364082896(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364080208(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364075120(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364076992(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364085872(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364083664(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364083472(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364084288(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364081648(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364081168(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364073344(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364079440(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364083088(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364078576(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364072912(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364076512(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364088464(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364083328(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364080352(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364088272(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364084816(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364086640(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364073824(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364083952(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364082560(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364081984(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364084192(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364086112(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364084528(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364086496(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364081408(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364073584(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364080640(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364077952(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364087360(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364087120(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364080016(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364078192(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364081024(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364081216(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364083568(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364087600(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364083712(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364082176(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364084336(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364076944(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364084960(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364081552(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364075792(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364083808(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364084096(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364073920(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364082272(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364077712(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364077280(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364076368(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364085440(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364079824(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364072816(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364076848(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364079680(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364081456(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364080832(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364085488(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364072960(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364085920(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364085344(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364078144(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364076704(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364088320(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364074352(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364073776(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364085248(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate mcu1_5367978976(_gate_p_0) _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8 {
  cu1_5368516240(pi/128) _gate_q_7, _gate_q_8;
  cx _gate_q_7, _gate_q_6;
  cu1_5368519984(-pi/128) _gate_q_6, _gate_q_8;
  cx _gate_q_7, _gate_q_6;
  cu1_5368516240(pi/128) _gate_q_6, _gate_q_8;
  cx _gate_q_6, _gate_q_5;
  cu1_5368523248(-pi/128) _gate_q_5, _gate_q_8;
  cx _gate_q_7, _gate_q_5;
  cu1_5368516240(pi/128) _gate_q_5, _gate_q_8;
  cx _gate_q_6, _gate_q_5;
  cu1_5368526032(-pi/128) _gate_q_5, _gate_q_8;
  cx _gate_q_7, _gate_q_5;
  cu1_5368516240(pi/128) _gate_q_5, _gate_q_8;
  cx _gate_q_5, _gate_q_4;
  cu1_5368522144(-pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_7, _gate_q_4;
  cu1_5368516240(pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_6, _gate_q_4;
  cu1_5368527568(-pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_7, _gate_q_4;
  cu1_5368516240(pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_5, _gate_q_4;
  cu1_5368523968(-pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_7, _gate_q_4;
  cu1_5368516240(pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_6, _gate_q_4;
  cu1_5368520272(-pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_7, _gate_q_4;
  cu1_5368516240(pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_4, _gate_q_3;
  cu1_5368520128(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5368516240(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_6, _gate_q_3;
  cu1_5368523488(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5368516240(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_5, _gate_q_3;
  cu1_5368524496(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5368516240(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_6, _gate_q_3;
  cu1_5368517776(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5368516240(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_4, _gate_q_3;
  cu1_5368515376(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5368516240(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_6, _gate_q_3;
  cu1_5368514272(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5368516240(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_5, _gate_q_3;
  cu1_5368526416(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5368516240(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_6, _gate_q_3;
  cu1_5368527088(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5368516240(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_3, _gate_q_2;
  cu1_5368524448(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368516240(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5368518880(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368516240(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_5, _gate_q_2;
  cu1_5368513264(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368516240(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5368526080(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368516240(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_4, _gate_q_2;
  cu1_5368517920(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368516240(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5368516816(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368516240(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_5, _gate_q_2;
  cu1_5368513072(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368516240(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5368524928(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368516240(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_3, _gate_q_2;
  cu1_5368515040(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368516240(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5368525264(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368516240(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_5, _gate_q_2;
  cu1_5368516384(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368516240(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5368515088(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368516240(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_4, _gate_q_2;
  cu1_5368521712(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368516240(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5368513840(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368516240(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_5, _gate_q_2;
  cu1_5368512976(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368516240(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5368519408(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5368516240(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_2, _gate_q_1;
  cu1_5368518304(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5368525072(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5368513216(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5368522816(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_4, _gate_q_1;
  cu1_5368514080(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5368515472(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5368527664(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5368521904(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_3, _gate_q_1;
  cu1_5368519072(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5368520032(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5368517488(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5368516480(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_4, _gate_q_1;
  cu1_5368527616(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5368519888(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5368528192(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5368527808(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_2, _gate_q_1;
  cu1_5368519840(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5368521808(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5368525168(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5368520992(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_4, _gate_q_1;
  cu1_5368523104(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5368518832(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5364083760(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5364082896(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_3, _gate_q_1;
  cu1_5364080208(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5364075120(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5364076992(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5364085872(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_4, _gate_q_1;
  cu1_5364083664(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5364083472(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5364084288(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5364081648(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5368516240(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_1, _gate_q_0;
  cu1_5364081168(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364073344(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5364079440(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364083088(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5364078576(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364072912(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5364076512(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364088464(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_3, _gate_q_0;
  cu1_5364083328(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364080352(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5364088272(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364084816(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5364086640(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364073824(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5364083952(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364082560(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_2, _gate_q_0;
  cu1_5364081984(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364084192(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5364086112(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364084528(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5364086496(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364081408(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5364073584(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364080640(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_3, _gate_q_0;
  cu1_5364077952(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364087360(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5364087120(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364080016(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5364078192(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364081024(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5364081216(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364083568(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_1, _gate_q_0;
  cu1_5364087600(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364083712(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5364082176(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364084336(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5364076944(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364084960(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5364081552(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364075792(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_3, _gate_q_0;
  cu1_5364083808(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364084096(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5364073920(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364082272(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5364077712(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364077280(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5364076368(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364085440(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_2, _gate_q_0;
  cu1_5364079824(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364072816(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5364076848(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364079680(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5364081456(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364080832(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5364085488(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364072960(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_3, _gate_q_0;
  cu1_5364085920(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364085344(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5364078144(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364076704(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5364088320(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364074352(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5364073776(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364085248(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5368516240(pi/128) _gate_q_0, _gate_q_8;
}
gate mcx _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8 {
  h _gate_q_8;
  mcu1_5367978976(pi) _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8;
  h _gate_q_8;
}