import sympy as sp
import cirq

def algorithm():
    q = cirq.LineQubit.range(4)
    c = cirq.Circuit()
    theta_0 = sp.Symbol('theta_0')
    phi_0 = sp.Symbol('phi_0')
    lambda_0 = sp.Symbol('lambda_0')
    c.append(cirq.rz(phi_0).on(q[0]))
    c.append(cirq.ry(theta_0).on(q[0]))
    c.append(cirq.rz(lambda_0).on(q[0]))
    theta_1 = sp.Symbol('theta_1')
    phi_1 = sp.Symbol('phi_1')
    lambda_1 = sp.Symbol('lambda_1')
    c.append(cirq.rz(phi_1).on(q[1]))
    c.append(cirq.ry(theta_1).on(q[1]))
    c.append(cirq.rz(lambda_1).on(q[1]))
    theta_2 = sp.Symbol('theta_2')
    phi_2 = sp.Symbol('phi_2')
    lambda_2 = sp.Symbol('lambda_2')
    c.append(cirq.rz(phi_2).on(q[2]))
    c.append(cirq.ry(theta_2).on(q[2]))
    c.append(cirq.rz(lambda_2).on(q[2]))
    theta_3 = sp.Symbol('theta_3')
    phi_3 = sp.Symbol('phi_3')
    lambda_3 = sp.Symbol('lambda_3')
    c.append(cirq.rz(phi_3).on(q[3]))
    c.append(cirq.ry(theta_3).on(q[3]))
    c.append(cirq.rz(lambda_3).on(q[3]))
    c.append(cirq.CNOT(q[0], q[1]))
    c.append(cirq.CNOT(q[0], q[2]))
    c.append(cirq.CNOT(q[0], q[3]))
    c.append(cirq.CNOT(q[1], q[2]))
    c.append(cirq.CNOT(q[1], q[3]))
    c.append(cirq.CNOT(q[2], q[3]))
    theta_4 = sp.Symbol('theta_4')
    phi_4 = sp.Symbol('phi_4')
    lambda_4 = sp.Symbol('lambda_4')
    c.append(cirq.rz(phi_4).on(q[0]))
    c.append(cirq.ry(theta_4).on(q[0]))
    c.append(cirq.rz(lambda_4).on(q[0]))
    theta_5 = sp.Symbol('theta_5')
    phi_5 = sp.Symbol('phi_5')
    lambda_5 = sp.Symbol('lambda_5')
    c.append(cirq.rz(phi_5).on(q[1]))
    c.append(cirq.ry(theta_5).on(q[1]))
    c.append(cirq.rz(lambda_5).on(q[1]))
    theta_6 = sp.Symbol('theta_6')
    phi_6 = sp.Symbol('phi_6')
    lambda_6 = sp.Symbol('lambda_6')
    c.append(cirq.rz(phi_6).on(q[2]))
    c.append(cirq.ry(theta_6).on(q[2]))
    c.append(cirq.rz(lambda_6).on(q[2]))
    theta_7 = sp.Symbol('theta_7')
    phi_7 = sp.Symbol('phi_7')
    lambda_7 = sp.Symbol('lambda_7')
    c.append(cirq.rz(phi_7).on(q[3]))
    c.append(cirq.ry(theta_7).on(q[3]))
    c.append(cirq.rz(lambda_7).on(q[3]))
