import cirq

def algorithm():
    qubits = cirq.LineQubit.range(12)
    circuit = cirq.Circuit()
    circuit.append(cirq.CNOT(qubits[7], qubits[1]))
    circuit.append(cirq.CNOT(qubits[8], qubits[1]))
    circuit.append(cirq.CNOT(qubits[10], qubits[11]))
    circuit.append(cirq.H(qubits[2]))
    circuit.append(cirq.CNOT(qubits[6], qubits[5]))
    circuit.append(cirq.CNOT(qubits[9], qubits[10]))
    circuit.append(cirq.H(qubits[10]))
    circuit.append(cirq.CNOT(qubits[2], qubits[8]))
    circuit.append(cirq.S(qubits[9]))
    circuit.append(cirq.S(qubits[7]))
    circuit.append(cirq.CNOT(qubits[6], qubits[2]))
    circuit.append(cirq.S(qubits[10]))
    circuit.append(cirq.S(qubits[6]))
    circuit.append(cirq.H(qubits[10]))
    circuit.append(cirq.H(qubits[7]))
    circuit.append(cirq.CNOT(qubits[1], qubits[9]))
    circuit.append(cirq.CNOT(qubits[7], qubits[1]))
    circuit.append(cirq.H(qubits[11]))
    circuit.append(cirq.H(qubits[9]))
    circuit.append(cirq.H(qubits[8]))
    circuit.append(cirq.S(qubits[2]))
    circuit.append(cirq.S(qubits[4]))
    circuit.append(cirq.H(qubits[7]))
    circuit.append(cirq.CNOT(qubits[10], qubits[7]))
    circuit.append(cirq.S(qubits[2]))
    circuit.append(cirq.CNOT(qubits[3], qubits[7]))
    circuit.append(cirq.S(qubits[9]))
    circuit.append(cirq.S(qubits[11]))
    circuit.append(cirq.S(qubits[1]))
    circuit.append(cirq.CNOT(qubits[7], qubits[3]))
    circuit.append(cirq.S(qubits[4]))
    circuit.append(cirq.S(qubits[3]))
    circuit.append(cirq.S(qubits[10]))
    circuit.append(cirq.CNOT(qubits[6], qubits[0]))
    circuit.append(cirq.S(qubits[1]))
    circuit.append(cirq.H(qubits[9]))
    circuit.append(cirq.S(qubits[6]))
    circuit.append(cirq.S(qubits[10]))
    circuit.append(cirq.CNOT(qubits[7], qubits[5]))
    circuit.append(cirq.CNOT(qubits[4], qubits[10]))
    circuit.append(cirq.S(qubits[5]))
    circuit.append(cirq.S(qubits[11]))
    circuit.append(cirq.S(qubits[11]))
    circuit.append(cirq.H(qubits[1]))
    circuit.append(cirq.H(qubits[4]))
    circuit.append(cirq.CNOT(qubits[10], qubits[7]))
    circuit.append(cirq.S(qubits[3]))
    circuit.append(cirq.CNOT(qubits[2], qubits[1]))
    circuit.append(cirq.S(qubits[4]))
    circuit.append(cirq.S(qubits[9]))
    circuit.append(cirq.CNOT(qubits[9], qubits[4]))
    circuit.append(cirq.H(qubits[2]))
    circuit.append(cirq.H(qubits[11]))
    circuit.append(cirq.CNOT(qubits[7], qubits[0]))
    circuit.append(cirq.S(qubits[1]))
    circuit.append(cirq.S(qubits[1]))
    circuit.append(cirq.S(qubits[10]))
    circuit.append(cirq.CNOT(qubits[10], qubits[6]))
    circuit.append(cirq.H(qubits[9]))
    circuit.append(cirq.H(qubits[9]))
    circuit.append(cirq.S(qubits[9]))
    circuit.append(cirq.CNOT(qubits[10], qubits[9]))
    circuit.append(cirq.CNOT(qubits[6], qubits[7]))
    circuit.append(cirq.H(qubits[10]))
    circuit.append(cirq.H(qubits[7]))
    circuit.append(cirq.CNOT(qubits[7], qubits[8]))
    circuit.append(cirq.H(qubits[7]))
    circuit.append(cirq.S(qubits[8]))
    circuit.append(cirq.CNOT(qubits[11], qubits[6]))
    circuit.append(cirq.H(qubits[3]))
    circuit.append(cirq.H(qubits[10]))
    circuit.append(cirq.H(qubits[4]))
    circuit.append(cirq.S(qubits[11]))
    circuit.append(cirq.S(qubits[0]))
    circuit.append(cirq.S(qubits[5]))
    circuit.append(cirq.CNOT(qubits[6], qubits[11]))
    circuit.append(cirq.H(qubits[1]))
    circuit.append(cirq.H(qubits[5]))
    circuit.append(cirq.CNOT(qubits[6], qubits[2]))
    circuit.append(cirq.S(qubits[3]))
    circuit.append(cirq.CNOT(qubits[2], qubits[6]))
    circuit.append(cirq.H(qubits[3]))
    circuit.append(cirq.H(qubits[0]))
    circuit.append(cirq.H(qubits[0]))
    circuit.append(cirq.H(qubits[0]))
    circuit.append(cirq.H(qubits[5]))
    circuit.append(cirq.S(qubits[0]))
    circuit.append(cirq.CNOT(qubits[9], qubits[10]))
    circuit.append(cirq.CNOT(qubits[2], qubits[1]))
    circuit.append(cirq.S(qubits[2]))
    circuit.append(cirq.CNOT(qubits[2], qubits[7]))
    circuit.append(cirq.H(qubits[6]))
    circuit.append(cirq.H(qubits[4]))
    circuit.append(cirq.CNOT(qubits[6], qubits[2]))
    circuit.append(cirq.H(qubits[11]))
    circuit.append(cirq.S(qubits[9]))
    circuit.append(cirq.H(qubits[11]))
    circuit.append(cirq.H(qubits[0]))
    circuit.append(cirq.S(qubits[2]))
    circuit.append(cirq.H(qubits[11]))
    circuit.append(cirq.S(qubits[11]))
    circuit.append(cirq.H(qubits[4]))
    circuit.append(cirq.S(qubits[8]))
    circuit.append(cirq.CNOT(qubits[8], qubits[10]))
    circuit.append(cirq.S(qubits[7]))
    circuit.append(cirq.CNOT(qubits[7], qubits[5]))
    circuit.append(cirq.H(qubits[11]))
    circuit.append(cirq.CNOT(qubits[4], qubits[7]))
    circuit.append(cirq.H(qubits[3]))
    circuit.append(cirq.S(qubits[7]))
    circuit.append(cirq.H(qubits[0]))
    circuit.append(cirq.CNOT(qubits[10], qubits[11]))
    circuit.append(cirq.CNOT(qubits[11], qubits[9]))
    circuit.append(cirq.S(qubits[0]))
    circuit.append(cirq.H(qubits[2]))
    circuit.append(cirq.H(qubits[4]))
    circuit.append(cirq.H(qubits[8]))
    circuit.append(cirq.CNOT(qubits[4], qubits[2]))
    circuit.append(cirq.H(qubits[2]))
    circuit.append(cirq.H(qubits[3]))
    circuit.append(cirq.S(qubits[11]))
    circuit.append(cirq.CNOT(qubits[8], qubits[4]))
    circuit.append(cirq.CNOT(qubits[4], qubits[8]))
    circuit.append(cirq.CNOT(qubits[1], qubits[3]))
    circuit.append(cirq.S(qubits[3]))
    circuit.append(cirq.S(qubits[8]))
    circuit.append(cirq.S(qubits[5]))
    circuit.append(cirq.CNOT(qubits[4], qubits[1]))
    circuit.append(cirq.S(qubits[5]))
    circuit.append(cirq.CNOT(qubits[4], qubits[6]))
    circuit.append(cirq.S(qubits[9]))
    circuit.append(cirq.S(qubits[3]))
    circuit.append(cirq.S(qubits[4]))
    circuit.append(cirq.H(qubits[1]))
    circuit.append(cirq.CNOT(qubits[0], qubits[4]))
    circuit.append(cirq.S(qubits[6]))
    circuit.append(cirq.H(qubits[3]))
    circuit.append(cirq.H(qubits[2]))
    circuit.append(cirq.CNOT(qubits[3], qubits[10]))
    circuit.append(cirq.CNOT(qubits[9], qubits[3]))
    circuit.append(cirq.H(qubits[8]))
    circuit.append(cirq.H(qubits[9]))
    circuit.append(cirq.CNOT(qubits[4], qubits[2]))
    circuit.append(cirq.CNOT(qubits[5], qubits[11]))
    circuit.append(cirq.H(qubits[9]))
    circuit.append(cirq.H(qubits[11]))
    circuit.append(cirq.S(qubits[6]))
    circuit.append(cirq.S(qubits[10]))
    circuit.append(cirq.H(qubits[8]))
    circuit.append(cirq.S(qubits[10]))
    circuit.append(cirq.H(qubits[10]))
    circuit.append(cirq.CNOT(qubits[9], qubits[1]))
    circuit.append(cirq.H(qubits[4]))
    circuit.append(cirq.CNOT(qubits[10], qubits[1]))
    circuit.append(cirq.H(qubits[11]))
    circuit.append(cirq.S(qubits[2]))
    circuit.append(cirq.S(qubits[11]))
    circuit.append(cirq.H(qubits[8]))
    circuit.append(cirq.H(qubits[7]))
    circuit.append(cirq.H(qubits[7]))
    circuit.append(cirq.S(qubits[9]))
    circuit.append(cirq.H(qubits[5]))
    circuit.append(cirq.CNOT(qubits[11], qubits[7]))
    circuit.append(cirq.S(qubits[8]))
    circuit.append(cirq.H(qubits[8]))
    circuit.append(cirq.CNOT(qubits[1], qubits[8]))
    circuit.append(cirq.CNOT(qubits[1], qubits[4]))
    circuit.append(cirq.CNOT(qubits[9], qubits[2]))
    circuit.append(cirq.H(qubits[1]))
    circuit.append(cirq.H(qubits[5]))
    circuit.append(cirq.S(qubits[5]))
    circuit.append(cirq.S(qubits[9]))
    circuit.append(cirq.H(qubits[0]))
    circuit.append(cirq.CNOT(qubits[10], qubits[5]))
    circuit.append(cirq.H(qubits[5]))
    circuit.append(cirq.S(qubits[11]))
    circuit.append(cirq.CNOT(qubits[1], qubits[6]))
    circuit.append(cirq.S(qubits[2]))
    circuit.append(cirq.CNOT(qubits[8], qubits[9]))
    circuit.append(cirq.H(qubits[5]))
    circuit.append(cirq.S(qubits[6]))
    circuit.append(cirq.CNOT(qubits[11], qubits[2]))
    circuit.append(cirq.CNOT(qubits[1], qubits[2]))
    circuit.append(cirq.CNOT(qubits[10], qubits[7]))
    circuit.append(cirq.CNOT(qubits[2], qubits[10]))
    circuit.append(cirq.CNOT(qubits[9], qubits[11]))
    circuit.append(cirq.S(qubits[11]))
    circuit.append(cirq.H(qubits[4]))
    circuit.append(cirq.S(qubits[3]))
    circuit.append(cirq.H(qubits[3]))
    circuit.append(cirq.H(qubits[11]))
    circuit.append(cirq.S(qubits[9]))
    circuit.append(cirq.S(qubits[2]))
    circuit.append(cirq.CNOT(qubits[10], qubits[5]))
    circuit.append(cirq.CNOT(qubits[2], qubits[9]))
    circuit.append(cirq.S(qubits[10]))
    circuit.append(cirq.H(qubits[10]))
    circuit.append(cirq.CNOT(qubits[10], qubits[7]))
    return circuit
