gate mcphase_5895250544(_gate_p_0) _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7 {
  cp(pi/128) _gate_q_6, _gate_q_7;
  cx _gate_q_6, _gate_q_5;
  cp(-pi/128) _gate_q_5, _gate_q_7;
  cx _gate_q_6, _gate_q_5;
  cp(pi/128) _gate_q_5, _gate_q_7;
  cx _gate_q_5, _gate_q_4;
  cp(-pi/128) _gate_q_4, _gate_q_7;
  cx _gate_q_6, _gate_q_4;
  cp(pi/128) _gate_q_4, _gate_q_7;
  cx _gate_q_5, _gate_q_4;
  cp(-pi/128) _gate_q_4, _gate_q_7;
  cx _gate_q_6, _gate_q_4;
  cp(pi/128) _gate_q_4, _gate_q_7;
  cx _gate_q_4, _gate_q_3;
  cp(-pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_6, _gate_q_3;
  cp(pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_5, _gate_q_3;
  cp(-pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_6, _gate_q_3;
  cp(pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_4, _gate_q_3;
  cp(-pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_6, _gate_q_3;
  cp(pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_5, _gate_q_3;
  cp(-pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_6, _gate_q_3;
  cp(pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_3, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_5, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_4, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_5, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_3, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_5, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_4, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_5, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_2, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_4, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_3, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_4, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_2, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_4, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_3, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_4, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_1, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_3, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_2, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_3, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_1, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_3, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_2, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_3, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
}
gate c8z _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8 {
  U(pi/2, 0, pi) _gate_q_8;
  cx _gate_q_8, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_8, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  U(pi/2, pi/4, -3*pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  p(-pi/4) _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  p(pi/4) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  U(pi/2, 0, 3*pi/4) _gate_q_4;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, -pi/4, 3*pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_8, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_8, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  p(-pi/4) _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  p(pi/4) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  U(pi/2, 0, 3*pi/4) _gate_q_4;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, 0, 3*pi/4) _gate_q_5;
  U(pi/4, pi/2, -pi/2) _gate_q_8;
  cx _gate_q_8, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_8, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  U(pi/2, pi/4, -3*pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_2;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_3;
  cx _gate_q_5, _gate_q_2;
  p(-pi/4) _gate_q_2;
  cx _gate_q_4, _gate_q_2;
  p(pi/4) _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  U(pi/2, 0, 3*pi/4) _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, -pi/4, 3*pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_8, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_8, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_2;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_3;
  cx _gate_q_5, _gate_q_2;
  p(-pi/4) _gate_q_2;
  cx _gate_q_4, _gate_q_2;
  p(pi/4) _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  U(pi/2, 0, 3*pi/4) _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, 0, 3*pi/4) _gate_q_3;
  U(pi/4, -pi/2, pi/2) _gate_q_8;
  cx _gate_q_8, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_8, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  U(pi/2, pi/4, -3*pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  p(-pi/4) _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  p(pi/4) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  U(pi/2, 0, 3*pi/4) _gate_q_4;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, -pi/4, 3*pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_8, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_8, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  p(-pi/4) _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  p(pi/4) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  U(pi/2, 0, 3*pi/4) _gate_q_4;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, 0, 3*pi/4) _gate_q_5;
  U(pi/4, pi/2, -pi/2) _gate_q_8;
  cx _gate_q_8, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_8, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  U(pi/2, pi/4, -3*pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_2;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_3;
  cx _gate_q_5, _gate_q_2;
  p(-pi/4) _gate_q_2;
  cx _gate_q_4, _gate_q_2;
  p(pi/4) _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  U(pi/2, 0, 3*pi/4) _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, -pi/4, 3*pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_8, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_8, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_2;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_3;
  cx _gate_q_5, _gate_q_2;
  p(-pi/4) _gate_q_2;
  cx _gate_q_4, _gate_q_2;
  p(pi/4) _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  U(pi/2, 0, 3*pi/4) _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, 0, 3*pi/4) _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_8;
  mcphase_5895250544(pi/2) _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7;
}
gate Oracle _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8 {
  x _gate_q_0;
  x _gate_q_1;
  x _gate_q_5;
  x _gate_q_6;
  c8z _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8;
  x _gate_q_0;
  x _gate_q_1;
  x _gate_q_5;
  x _gate_q_6;
}
gate cu1_5895168384(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
}
gate cu1_5895164256(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895175632(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895172512(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895171072(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895163392(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895169632(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895168768(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895175152(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895168096(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895165024(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895175872(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895163440(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895170448(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895162528(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895176016(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895175776(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895162432(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895163536(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895172032(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895166032(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895170880(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895174240(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895166704(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895173232(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895173616(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895164016(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895160560(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895171168(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895167952(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895166848(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895169488(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895172128(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895170400(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895171600(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895160992(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895175344(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895176112(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895169152(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895162144(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895170928(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895174000(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895173856(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895170592(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895166464(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895171456(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895166128(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895171744(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895161568(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895175824(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895169536(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895170736(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895257744(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895256688(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895256496(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895256544(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895256400(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895243152(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895245120(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895242432(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895257792(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895257120(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895253568(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895241952(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895245168(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895256064(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895257888(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895243488(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895257936(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895257168(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895257024(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895256016(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895251936(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895248048(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895242768(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895247856(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895251696(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895257216(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895252560(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895250784(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895257264(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895252080(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895252944(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895242048(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895249296(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895251408(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368515568(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368521808(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368526560(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368518208(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368518064(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368519696(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368521712(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368528624(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368515088(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368514080(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368516384(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368528672(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368526080(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368513216(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368518880(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368518304(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368527424(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368519744(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368518688(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368513648(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368514560(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368517776(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368521280(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368514176(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368526032(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368518832(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368527328(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368522144(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368526416(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368527088(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368513072(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368525552(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368528000(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368523104(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368516240(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368519984(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368520128(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368523728(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368523488(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368525888(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368520560(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5368515664(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate mcu1_5895174672(_gate_p_0) _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8 {
  cu1_5895168384(pi/128) _gate_q_7, _gate_q_8;
  cx _gate_q_7, _gate_q_6;
  cu1_5895164256(-pi/128) _gate_q_6, _gate_q_8;
  cx _gate_q_7, _gate_q_6;
  cu1_5895168384(pi/128) _gate_q_6, _gate_q_8;
  cx _gate_q_6, _gate_q_5;
  cu1_5895175632(-pi/128) _gate_q_5, _gate_q_8;
  cx _gate_q_7, _gate_q_5;
  cu1_5895168384(pi/128) _gate_q_5, _gate_q_8;
  cx _gate_q_6, _gate_q_5;
  cu1_5895172512(-pi/128) _gate_q_5, _gate_q_8;
  cx _gate_q_7, _gate_q_5;
  cu1_5895168384(pi/128) _gate_q_5, _gate_q_8;
  cx _gate_q_5, _gate_q_4;
  cu1_5895171072(-pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_7, _gate_q_4;
  cu1_5895168384(pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_6, _gate_q_4;
  cu1_5895163392(-pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_7, _gate_q_4;
  cu1_5895168384(pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_5, _gate_q_4;
  cu1_5895169632(-pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_7, _gate_q_4;
  cu1_5895168384(pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_6, _gate_q_4;
  cu1_5895168768(-pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_7, _gate_q_4;
  cu1_5895168384(pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_4, _gate_q_3;
  cu1_5895175152(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5895168384(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_6, _gate_q_3;
  cu1_5895168096(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5895168384(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_5, _gate_q_3;
  cu1_5895165024(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5895168384(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_6, _gate_q_3;
  cu1_5895175872(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5895168384(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_4, _gate_q_3;
  cu1_5895163440(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5895168384(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_6, _gate_q_3;
  cu1_5895170448(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5895168384(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_5, _gate_q_3;
  cu1_5895162528(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5895168384(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_6, _gate_q_3;
  cu1_5895176016(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5895168384(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_3, _gate_q_2;
  cu1_5895175776(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895168384(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5895162432(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895168384(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_5, _gate_q_2;
  cu1_5895163536(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895168384(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5895172032(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895168384(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_4, _gate_q_2;
  cu1_5895166032(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895168384(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5895170880(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895168384(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_5, _gate_q_2;
  cu1_5895174240(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895168384(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5895166704(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895168384(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_3, _gate_q_2;
  cu1_5895173232(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895168384(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5895173616(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895168384(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_5, _gate_q_2;
  cu1_5895164016(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895168384(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5895160560(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895168384(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_4, _gate_q_2;
  cu1_5895171168(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895168384(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5895167952(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895168384(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_5, _gate_q_2;
  cu1_5895166848(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895168384(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5895169488(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895168384(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_2, _gate_q_1;
  cu1_5895172128(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895170400(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5895171600(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895160992(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_4, _gate_q_1;
  cu1_5895175344(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895176112(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5895169152(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895162144(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_3, _gate_q_1;
  cu1_5895170928(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895174000(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5895173856(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895170592(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_4, _gate_q_1;
  cu1_5895166464(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895171456(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5895166128(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895171744(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_2, _gate_q_1;
  cu1_5895161568(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895175824(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5895169536(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895170736(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_4, _gate_q_1;
  cu1_5895257744(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895256688(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5895256496(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895256544(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_3, _gate_q_1;
  cu1_5895256400(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895243152(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5895245120(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895242432(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_4, _gate_q_1;
  cu1_5895257792(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895257120(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5895253568(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895241952(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895168384(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_1, _gate_q_0;
  cu1_5895245168(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895256064(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5895257888(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895243488(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5895257936(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895257168(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5895257024(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895256016(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_3, _gate_q_0;
  cu1_5895251936(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895248048(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5895242768(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895247856(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5895251696(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895257216(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5895252560(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895250784(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_2, _gate_q_0;
  cu1_5895257264(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895252080(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5895252944(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895242048(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5895249296(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895251408(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5368515568(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368521808(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_3, _gate_q_0;
  cu1_5368526560(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368518208(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5368518064(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368519696(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5368521712(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368528624(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5368515088(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368514080(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_1, _gate_q_0;
  cu1_5368516384(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368528672(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5368526080(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368513216(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5368518880(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368518304(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5368527424(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368519744(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_3, _gate_q_0;
  cu1_5368518688(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368513648(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5368514560(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368517776(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5368521280(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368514176(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5368526032(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368518832(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_2, _gate_q_0;
  cu1_5368527328(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368522144(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5368526416(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368527088(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5368513072(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368525552(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5368528000(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368523104(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_3, _gate_q_0;
  cu1_5368516240(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368519984(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5368520128(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368523728(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5368523488(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368525888(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5368520560(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5368515664(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895168384(pi/128) _gate_q_0, _gate_q_8;
}
gate mcx _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8 {
  h _gate_q_8;
  mcu1_5895174672(pi) _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8;
  h _gate_q_8;
}