OPENQASM 3.0;
include "stdgates.inc";
include "oracle.inc";
bit[4] c;
qubit[8] q;
h q[0];
h q[1];
h q[2];
h q[3];
Oracle q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7];
h q[0];
h q[1];
h q[2];
h q[3];
c[0] = measure q[0];
c[1] = measure q[1];
c[2] = measure q[2];
c[3] = measure q[3];
