import cirq

def oracle_circuit():
    qubits = cirq.LineQubit.range(16)
    circuit = cirq.Circuit()
    anc0 = qubits[13]
    anc1 = qubits[14]
    outq = qubits[15]
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[0], qubits[4], anc0, anc1))
    circuit.append(cirq.CCX(qubits[0], qubits[4], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[0], qubits[7], anc0, anc1))
    circuit.append(cirq.CCX(qubits[0], qubits[7], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[0], qubits[9], anc0, anc1))
    circuit.append(cirq.CCX(qubits[0], qubits[9], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[0], qubits[11], anc0, anc1))
    circuit.append(cirq.CCX(qubits[0], qubits[11], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[0], qubits[12], anc0, anc1))
    circuit.append(cirq.CCX(qubits[0], qubits[12], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[1], qubits[2], anc0, anc1))
    circuit.append(cirq.CCX(qubits[1], qubits[2], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[1], qubits[3], anc0, anc1))
    circuit.append(cirq.CCX(qubits[1], qubits[3], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[1], qubits[6], anc0, anc1))
    circuit.append(cirq.CCX(qubits[1], qubits[6], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[1], qubits[7], anc0, anc1))
    circuit.append(cirq.CCX(qubits[1], qubits[7], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[1], qubits[10], anc0, anc1))
    circuit.append(cirq.CCX(qubits[1], qubits[10], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[2], qubits[4], anc0, anc1))
    circuit.append(cirq.CCX(qubits[2], qubits[4], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[2], qubits[6], anc0, anc1))
    circuit.append(cirq.CCX(qubits[2], qubits[6], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[2], qubits[7], anc0, anc1))
    circuit.append(cirq.CCX(qubits[2], qubits[7], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[2], qubits[8], anc0, anc1))
    circuit.append(cirq.CCX(qubits[2], qubits[8], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[2], qubits[10], anc0, anc1))
    circuit.append(cirq.CCX(qubits[2], qubits[10], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[2], qubits[11], anc0, anc1))
    circuit.append(cirq.CCX(qubits[2], qubits[11], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[2], qubits[12], anc0, anc1))
    circuit.append(cirq.CCX(qubits[2], qubits[12], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[3], qubits[4], anc0, anc1))
    circuit.append(cirq.CCX(qubits[3], qubits[4], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[3], qubits[5], anc0, anc1))
    circuit.append(cirq.CCX(qubits[3], qubits[5], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[3], qubits[9], anc0, anc1))
    circuit.append(cirq.CCX(qubits[3], qubits[9], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[3], qubits[10], anc0, anc1))
    circuit.append(cirq.CCX(qubits[3], qubits[10], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[3], qubits[12], anc0, anc1))
    circuit.append(cirq.CCX(qubits[3], qubits[12], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[4], qubits[6], anc0, anc1))
    circuit.append(cirq.CCX(qubits[4], qubits[6], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[4], qubits[7], anc0, anc1))
    circuit.append(cirq.CCX(qubits[4], qubits[7], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[4], qubits[9], anc0, anc1))
    circuit.append(cirq.CCX(qubits[4], qubits[9], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[4], qubits[10], anc0, anc1))
    circuit.append(cirq.CCX(qubits[4], qubits[10], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[5], qubits[6], anc0, anc1))
    circuit.append(cirq.CCX(qubits[5], qubits[6], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[5], qubits[7], anc0, anc1))
    circuit.append(cirq.CCX(qubits[5], qubits[7], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[5], qubits[9], anc0, anc1))
    circuit.append(cirq.CCX(qubits[5], qubits[9], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[5], qubits[11], anc0, anc1))
    circuit.append(cirq.CCX(qubits[5], qubits[11], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[6], qubits[7], anc0, anc1))
    circuit.append(cirq.CCX(qubits[6], qubits[7], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[6], qubits[8], anc0, anc1))
    circuit.append(cirq.CCX(qubits[6], qubits[8], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[6], qubits[9], anc0, anc1))
    circuit.append(cirq.CCX(qubits[6], qubits[9], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[6], qubits[11], anc0, anc1))
    circuit.append(cirq.CCX(qubits[6], qubits[11], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[6], qubits[12], anc0, anc1))
    circuit.append(cirq.CCX(qubits[6], qubits[12], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[7], qubits[8], anc0, anc1))
    circuit.append(cirq.CCX(qubits[7], qubits[8], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[7], qubits[9], anc0, anc1))
    circuit.append(cirq.CCX(qubits[7], qubits[9], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[7], qubits[10], anc0, anc1))
    circuit.append(cirq.CCX(qubits[7], qubits[10], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[7], qubits[11], anc0, anc1))
    circuit.append(cirq.CCX(qubits[7], qubits[11], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[7], qubits[12], anc0, anc1))
    circuit.append(cirq.CCX(qubits[7], qubits[12], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[8], qubits[9], anc0, anc1))
    circuit.append(cirq.CCX(qubits[8], qubits[9], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[8], qubits[10], anc0, anc1))
    circuit.append(cirq.CCX(qubits[8], qubits[10], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[8], qubits[12], anc0, anc1))
    circuit.append(cirq.CCX(qubits[8], qubits[12], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[9], qubits[12], anc0, anc1))
    circuit.append(cirq.CCX(qubits[9], qubits[12], anc0))
    circuit.append(cirq.CCX(anc0, anc1, outq))
    circuit.append(cirq.CCX(qubits[9], qubits[12], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[9], qubits[12], anc0, anc1))
    circuit.append(cirq.CCX(qubits[8], qubits[12], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[8], qubits[12], anc0, anc1))
    circuit.append(cirq.CCX(qubits[8], qubits[10], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[8], qubits[10], anc0, anc1))
    circuit.append(cirq.CCX(qubits[8], qubits[9], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[8], qubits[9], anc0, anc1))
    circuit.append(cirq.CCX(qubits[7], qubits[12], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[7], qubits[12], anc0, anc1))
    circuit.append(cirq.CCX(qubits[7], qubits[11], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[7], qubits[11], anc0, anc1))
    circuit.append(cirq.CCX(qubits[7], qubits[10], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[7], qubits[10], anc0, anc1))
    circuit.append(cirq.CCX(qubits[7], qubits[9], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[7], qubits[9], anc0, anc1))
    circuit.append(cirq.CCX(qubits[7], qubits[8], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[7], qubits[8], anc0, anc1))
    circuit.append(cirq.CCX(qubits[6], qubits[12], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[6], qubits[12], anc0, anc1))
    circuit.append(cirq.CCX(qubits[6], qubits[11], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[6], qubits[11], anc0, anc1))
    circuit.append(cirq.CCX(qubits[6], qubits[9], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[6], qubits[9], anc0, anc1))
    circuit.append(cirq.CCX(qubits[6], qubits[8], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[6], qubits[8], anc0, anc1))
    circuit.append(cirq.CCX(qubits[6], qubits[7], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[6], qubits[7], anc0, anc1))
    circuit.append(cirq.CCX(qubits[5], qubits[11], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[5], qubits[11], anc0, anc1))
    circuit.append(cirq.CCX(qubits[5], qubits[9], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[5], qubits[9], anc0, anc1))
    circuit.append(cirq.CCX(qubits[5], qubits[7], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[5], qubits[7], anc0, anc1))
    circuit.append(cirq.CCX(qubits[5], qubits[6], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[5], qubits[6], anc0, anc1))
    circuit.append(cirq.CCX(qubits[4], qubits[10], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[4], qubits[10], anc0, anc1))
    circuit.append(cirq.CCX(qubits[4], qubits[9], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[4], qubits[9], anc0, anc1))
    circuit.append(cirq.CCX(qubits[4], qubits[7], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[4], qubits[7], anc0, anc1))
    circuit.append(cirq.CCX(qubits[4], qubits[6], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[4], qubits[6], anc0, anc1))
    circuit.append(cirq.CCX(qubits[3], qubits[12], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[3], qubits[12], anc0, anc1))
    circuit.append(cirq.CCX(qubits[3], qubits[10], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[3], qubits[10], anc0, anc1))
    circuit.append(cirq.CCX(qubits[3], qubits[9], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[3], qubits[9], anc0, anc1))
    circuit.append(cirq.CCX(qubits[3], qubits[5], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[3], qubits[5], anc0, anc1))
    circuit.append(cirq.CCX(qubits[3], qubits[4], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[3], qubits[4], anc0, anc1))
    circuit.append(cirq.CCX(qubits[2], qubits[12], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[2], qubits[12], anc0, anc1))
    circuit.append(cirq.CCX(qubits[2], qubits[11], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[2], qubits[11], anc0, anc1))
    circuit.append(cirq.CCX(qubits[2], qubits[10], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[2], qubits[10], anc0, anc1))
    circuit.append(cirq.CCX(qubits[2], qubits[8], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[2], qubits[8], anc0, anc1))
    circuit.append(cirq.CCX(qubits[2], qubits[7], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[2], qubits[7], anc0, anc1))
    circuit.append(cirq.CCX(qubits[2], qubits[6], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[2], qubits[6], anc0, anc1))
    circuit.append(cirq.CCX(qubits[2], qubits[4], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[2], qubits[4], anc0, anc1))
    circuit.append(cirq.CCX(qubits[1], qubits[10], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[1], qubits[10], anc0, anc1))
    circuit.append(cirq.CCX(qubits[1], qubits[7], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[1], qubits[7], anc0, anc1))
    circuit.append(cirq.CCX(qubits[1], qubits[6], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[1], qubits[6], anc0, anc1))
    circuit.append(cirq.CCX(qubits[1], qubits[3], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[1], qubits[3], anc0, anc1))
    circuit.append(cirq.CCX(qubits[1], qubits[2], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[1], qubits[2], anc0, anc1))
    circuit.append(cirq.CCX(qubits[0], qubits[12], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[0], qubits[12], anc0, anc1))
    circuit.append(cirq.CCX(qubits[0], qubits[11], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[0], qubits[11], anc0, anc1))
    circuit.append(cirq.CCX(qubits[0], qubits[9], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[0], qubits[9], anc0, anc1))
    circuit.append(cirq.CCX(qubits[0], qubits[7], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[0], qubits[7], anc0, anc1))
    circuit.append(cirq.CCX(qubits[0], qubits[4], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[0], qubits[4], anc0, anc1))
    return circuit
