import cirq

def oracle_circuit():
    qubits = cirq.LineQubit.range(13)
    circuit = cirq.Circuit()
    anc0 = qubits[10]
    anc1 = qubits[11]
    outq = qubits[12]
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[0], qubits[4], anc0, anc1))
    circuit.append(cirq.CCX(qubits[0], qubits[4], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[0], qubits[8], anc0, anc1))
    circuit.append(cirq.CCX(qubits[0], qubits[8], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[1], qubits[3], anc0, anc1))
    circuit.append(cirq.CCX(qubits[1], qubits[3], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[1], qubits[6], anc0, anc1))
    circuit.append(cirq.CCX(qubits[1], qubits[6], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[1], qubits[8], anc0, anc1))
    circuit.append(cirq.CCX(qubits[1], qubits[8], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[1], qubits[9], anc0, anc1))
    circuit.append(cirq.CCX(qubits[1], qubits[9], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[2], qubits[5], anc0, anc1))
    circuit.append(cirq.CCX(qubits[2], qubits[5], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[2], qubits[7], anc0, anc1))
    circuit.append(cirq.CCX(qubits[2], qubits[7], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[2], qubits[8], anc0, anc1))
    circuit.append(cirq.CCX(qubits[2], qubits[8], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[2], qubits[9], anc0, anc1))
    circuit.append(cirq.CCX(qubits[2], qubits[9], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[3], qubits[4], anc0, anc1))
    circuit.append(cirq.CCX(qubits[3], qubits[4], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[3], qubits[5], anc0, anc1))
    circuit.append(cirq.CCX(qubits[3], qubits[5], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[3], qubits[7], anc0, anc1))
    circuit.append(cirq.CCX(qubits[3], qubits[7], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[4], qubits[6], anc0, anc1))
    circuit.append(cirq.CCX(qubits[4], qubits[6], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[4], qubits[8], anc0, anc1))
    circuit.append(cirq.CCX(qubits[4], qubits[8], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[4], qubits[9], anc0, anc1))
    circuit.append(cirq.CCX(qubits[4], qubits[9], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[5], qubits[6], anc0, anc1))
    circuit.append(cirq.CCX(qubits[5], qubits[6], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[6], qubits[8], anc0, anc1))
    circuit.append(cirq.CCX(qubits[6], qubits[8], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[6], qubits[9], anc0, anc1))
    circuit.append(cirq.CCX(qubits[6], qubits[9], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[7], qubits[8], anc0, anc1))
    circuit.append(cirq.CCX(qubits[7], qubits[8], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[8], qubits[9], anc0, anc1))
    circuit.append(cirq.CCX(qubits[8], qubits[9], anc0))
    circuit.append(cirq.CCX(anc0, anc1, outq))
    circuit.append(cirq.CCX(qubits[8], qubits[9], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[8], qubits[9], anc0, anc1))
    circuit.append(cirq.CCX(qubits[7], qubits[8], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[7], qubits[8], anc0, anc1))
    circuit.append(cirq.CCX(qubits[6], qubits[9], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[6], qubits[9], anc0, anc1))
    circuit.append(cirq.CCX(qubits[6], qubits[8], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[6], qubits[8], anc0, anc1))
    circuit.append(cirq.CCX(qubits[5], qubits[6], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[5], qubits[6], anc0, anc1))
    circuit.append(cirq.CCX(qubits[4], qubits[9], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[4], qubits[9], anc0, anc1))
    circuit.append(cirq.CCX(qubits[4], qubits[8], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[4], qubits[8], anc0, anc1))
    circuit.append(cirq.CCX(qubits[4], qubits[6], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[4], qubits[6], anc0, anc1))
    circuit.append(cirq.CCX(qubits[3], qubits[7], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[3], qubits[7], anc0, anc1))
    circuit.append(cirq.CCX(qubits[3], qubits[5], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[3], qubits[5], anc0, anc1))
    circuit.append(cirq.CCX(qubits[3], qubits[4], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[3], qubits[4], anc0, anc1))
    circuit.append(cirq.CCX(qubits[2], qubits[9], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[2], qubits[9], anc0, anc1))
    circuit.append(cirq.CCX(qubits[2], qubits[8], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[2], qubits[8], anc0, anc1))
    circuit.append(cirq.CCX(qubits[2], qubits[7], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[2], qubits[7], anc0, anc1))
    circuit.append(cirq.CCX(qubits[2], qubits[5], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[2], qubits[5], anc0, anc1))
    circuit.append(cirq.CCX(qubits[1], qubits[9], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[1], qubits[9], anc0, anc1))
    circuit.append(cirq.CCX(qubits[1], qubits[8], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[1], qubits[8], anc0, anc1))
    circuit.append(cirq.CCX(qubits[1], qubits[6], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[1], qubits[6], anc0, anc1))
    circuit.append(cirq.CCX(qubits[1], qubits[3], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[1], qubits[3], anc0, anc1))
    circuit.append(cirq.CCX(qubits[0], qubits[8], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[0], qubits[8], anc0, anc1))
    circuit.append(cirq.CCX(qubits[0], qubits[4], anc0))
    circuit.append(cirq.X.controlled(num_controls=3).on(qubits[0], qubits[4], anc0, anc1))
    return circuit
