import cirq

def algorithm():
    qubits = cirq.LineQubit.range(7)
    circuit = cirq.Circuit()
    circuit.append(cirq.CNOT(qubits[4], qubits[0]))
    circuit.append(cirq.S(qubits[6]))
    circuit.append(cirq.S(qubits[1]))
    circuit.append(cirq.T(qubits[4]))
    circuit.append(cirq.T(qubits[4]))
    circuit.append(cirq.CNOT(qubits[6], qubits[5]))
    circuit.append(cirq.CNOT(qubits[0], qubits[2]))
    circuit.append(cirq.S(qubits[6]))
    circuit.append(cirq.CNOT(qubits[1], qubits[0]))
    circuit.append(cirq.H(qubits[0]))
    circuit.append(cirq.CNOT(qubits[3], qubits[2]))
    circuit.append(cirq.H(qubits[6]))
    circuit.append(cirq.CNOT(qubits[5], qubits[3]))
    circuit.append(cirq.H(qubits[0]))
    circuit.append(cirq.CNOT(qubits[6], qubits[2]))
    circuit.append(cirq.H(qubits[5]))
    circuit.append(cirq.CNOT(qubits[6], qubits[1]))
    circuit.append(cirq.S(qubits[6]))
    circuit.append(cirq.H(qubits[2]))
    circuit.append(cirq.T(qubits[3]))
    circuit.append(cirq.S(qubits[5]))
    circuit.append(cirq.T(qubits[0]))
    circuit.append(cirq.S(qubits[2]))
    circuit.append(cirq.T(qubits[2]))
    circuit.append(cirq.H(qubits[3]))
    circuit.append(cirq.T(qubits[5]))
    circuit.append(cirq.CNOT(qubits[6], qubits[5]))
    circuit.append(cirq.T(qubits[2]))
    circuit.append(cirq.S(qubits[6]))
    circuit.append(cirq.H(qubits[0]))
    circuit.append(cirq.H(qubits[4]))
    circuit.append(cirq.CNOT(qubits[3], qubits[5]))
    circuit.append(cirq.CNOT(qubits[1], qubits[4]))
    circuit.append(cirq.T(qubits[1]))
    circuit.append(cirq.T(qubits[5]))
    circuit.append(cirq.CNOT(qubits[6], qubits[4]))
    circuit.append(cirq.S(qubits[3]))
    circuit.append(cirq.CNOT(qubits[5], qubits[2]))
    circuit.append(cirq.CNOT(qubits[2], qubits[4]))
    circuit.append(cirq.S(qubits[4]))
    circuit.append(cirq.T(qubits[4]))
    circuit.append(cirq.T(qubits[1]))
    circuit.append(cirq.H(qubits[2]))
    circuit.append(cirq.H(qubits[5]))
    circuit.append(cirq.S(qubits[6]))
    circuit.append(cirq.S(qubits[1]))
    circuit.append(cirq.T(qubits[4]))
    circuit.append(cirq.CNOT(qubits[0], qubits[6]))
    circuit.append(cirq.T(qubits[3]))
    circuit.append(cirq.T(qubits[6]))
    circuit.append(cirq.T(qubits[0]))
    circuit.append(cirq.S(qubits[6]))
    circuit.append(cirq.H(qubits[2]))
    circuit.append(cirq.H(qubits[0]))
    circuit.append(cirq.S(qubits[4]))
    circuit.append(cirq.T(qubits[1]))
    circuit.append(cirq.CNOT(qubits[4], qubits[2]))
    circuit.append(cirq.CNOT(qubits[3], qubits[6]))
    circuit.append(cirq.S(qubits[5]))
    circuit.append(cirq.CNOT(qubits[5], qubits[2]))
    circuit.append(cirq.CNOT(qubits[0], qubits[6]))
    circuit.append(cirq.CNOT(qubits[1], qubits[4]))
    circuit.append(cirq.CNOT(qubits[0], qubits[4]))
    circuit.append(cirq.CNOT(qubits[2], qubits[1]))
    circuit.append(cirq.T(qubits[4]))
    circuit.append(cirq.S(qubits[0]))
    circuit.append(cirq.T(qubits[1]))
    circuit.append(cirq.H(qubits[3]))
    circuit.append(cirq.CNOT(qubits[4], qubits[5]))
    circuit.append(cirq.CNOT(qubits[0], qubits[5]))
    circuit.append(cirq.H(qubits[4]))
    circuit.append(cirq.T(qubits[4]))
    circuit.append(cirq.CNOT(qubits[0], qubits[4]))
    circuit.append(cirq.CNOT(qubits[2], qubits[1]))
    circuit.append(cirq.H(qubits[4]))
    circuit.append(cirq.T(qubits[5]))
    circuit.append(cirq.CNOT(qubits[6], qubits[3]))
    circuit.append(cirq.T(qubits[5]))
    circuit.append(cirq.H(qubits[5]))
    circuit.append(cirq.T(qubits[5]))
    circuit.append(cirq.S(qubits[2]))
    circuit.append(cirq.CNOT(qubits[3], qubits[6]))
    circuit.append(cirq.T(qubits[1]))
    return circuit
