import cirq

def algorithm():
    n = 24
    qubits = cirq.LineQubit.range(n)
    circuit = cirq.Circuit()
    # Alice prepares states (X**bit then H**basis)
    circuit.append(cirq.X(qubits[0])**0)
    circuit.append(cirq.H(qubits[0])**0)
    circuit.append(cirq.X(qubits[1])**0)
    circuit.append(cirq.H(qubits[1])**0)
    circuit.append(cirq.X(qubits[2])**1)
    circuit.append(cirq.H(qubits[2])**1)
    circuit.append(cirq.X(qubits[3])**1)
    circuit.append(cirq.H(qubits[3])**1)
    circuit.append(cirq.X(qubits[4])**0)
    circuit.append(cirq.H(qubits[4])**0)
    circuit.append(cirq.X(qubits[5])**1)
    circuit.append(cirq.H(qubits[5])**0)
    circuit.append(cirq.X(qubits[6])**0)
    circuit.append(cirq.H(qubits[6])**1)
    circuit.append(cirq.X(qubits[7])**1)
    circuit.append(cirq.H(qubits[7])**1)
    circuit.append(cirq.X(qubits[8])**1)
    circuit.append(cirq.H(qubits[8])**1)
    circuit.append(cirq.X(qubits[9])**0)
    circuit.append(cirq.H(qubits[9])**0)
    circuit.append(cirq.X(qubits[10])**1)
    circuit.append(cirq.H(qubits[10])**0)
    circuit.append(cirq.X(qubits[11])**0)
    circuit.append(cirq.H(qubits[11])**1)
    circuit.append(cirq.X(qubits[12])**0)
    circuit.append(cirq.H(qubits[12])**0)
    circuit.append(cirq.X(qubits[13])**0)
    circuit.append(cirq.H(qubits[13])**0)
    circuit.append(cirq.X(qubits[14])**0)
    circuit.append(cirq.H(qubits[14])**1)
    circuit.append(cirq.X(qubits[15])**1)
    circuit.append(cirq.H(qubits[15])**1)
    circuit.append(cirq.X(qubits[16])**0)
    circuit.append(cirq.H(qubits[16])**1)
    circuit.append(cirq.X(qubits[17])**1)
    circuit.append(cirq.H(qubits[17])**1)
    circuit.append(cirq.X(qubits[18])**0)
    circuit.append(cirq.H(qubits[18])**0)
    circuit.append(cirq.X(qubits[19])**0)
    circuit.append(cirq.H(qubits[19])**0)
    circuit.append(cirq.X(qubits[20])**0)
    circuit.append(cirq.H(qubits[20])**1)
    circuit.append(cirq.X(qubits[21])**0)
    circuit.append(cirq.H(qubits[21])**0)
    circuit.append(cirq.X(qubits[22])**0)
    circuit.append(cirq.H(qubits[22])**1)
    circuit.append(cirq.X(qubits[23])**1)
    circuit.append(cirq.H(qubits[23])**0)

    # Eve intercept (random basis baked), using PhaseDampingChannel(gamma)
    circuit.append(cirq.H(qubits[0])**0)
    circuit.append(cirq.PhaseDampingChannel(gamma=1).on(qubits[0]))
    circuit.append(cirq.H(qubits[0])**0)
    circuit.append(cirq.H(qubits[1])**1)
    circuit.append(cirq.PhaseDampingChannel(gamma=1).on(qubits[1]))
    circuit.append(cirq.H(qubits[1])**1)
    circuit.append(cirq.H(qubits[2])**1)
    circuit.append(cirq.PhaseDampingChannel(gamma=1).on(qubits[2]))
    circuit.append(cirq.H(qubits[2])**1)
    circuit.append(cirq.H(qubits[3])**0)
    circuit.append(cirq.PhaseDampingChannel(gamma=1).on(qubits[3]))
    circuit.append(cirq.H(qubits[3])**0)
    circuit.append(cirq.H(qubits[4])**0)
    circuit.append(cirq.PhaseDampingChannel(gamma=1).on(qubits[4]))
    circuit.append(cirq.H(qubits[4])**0)
    circuit.append(cirq.H(qubits[5])**1)
    circuit.append(cirq.PhaseDampingChannel(gamma=1).on(qubits[5]))
    circuit.append(cirq.H(qubits[5])**1)
    circuit.append(cirq.H(qubits[6])**1)
    circuit.append(cirq.PhaseDampingChannel(gamma=1).on(qubits[6]))
    circuit.append(cirq.H(qubits[6])**1)
    circuit.append(cirq.H(qubits[7])**0)
    circuit.append(cirq.PhaseDampingChannel(gamma=1).on(qubits[7]))
    circuit.append(cirq.H(qubits[7])**0)
    circuit.append(cirq.H(qubits[8])**1)
    circuit.append(cirq.PhaseDampingChannel(gamma=1).on(qubits[8]))
    circuit.append(cirq.H(qubits[8])**1)
    circuit.append(cirq.H(qubits[9])**0)
    circuit.append(cirq.PhaseDampingChannel(gamma=1).on(qubits[9]))
    circuit.append(cirq.H(qubits[9])**0)
    circuit.append(cirq.H(qubits[10])**0)
    circuit.append(cirq.PhaseDampingChannel(gamma=1).on(qubits[10]))
    circuit.append(cirq.H(qubits[10])**0)
    circuit.append(cirq.H(qubits[11])**0)
    circuit.append(cirq.PhaseDampingChannel(gamma=1).on(qubits[11]))
    circuit.append(cirq.H(qubits[11])**0)
    circuit.append(cirq.H(qubits[12])**0)
    circuit.append(cirq.PhaseDampingChannel(gamma=1).on(qubits[12]))
    circuit.append(cirq.H(qubits[12])**0)
    circuit.append(cirq.H(qubits[13])**1)
    circuit.append(cirq.PhaseDampingChannel(gamma=1).on(qubits[13]))
    circuit.append(cirq.H(qubits[13])**1)
    circuit.append(cirq.H(qubits[14])**1)
    circuit.append(cirq.PhaseDampingChannel(gamma=1).on(qubits[14]))
    circuit.append(cirq.H(qubits[14])**1)
    circuit.append(cirq.H(qubits[15])**1)
    circuit.append(cirq.PhaseDampingChannel(gamma=1).on(qubits[15]))
    circuit.append(cirq.H(qubits[15])**1)
    circuit.append(cirq.H(qubits[16])**1)
    circuit.append(cirq.PhaseDampingChannel(gamma=1).on(qubits[16]))
    circuit.append(cirq.H(qubits[16])**1)
    circuit.append(cirq.H(qubits[17])**0)
    circuit.append(cirq.PhaseDampingChannel(gamma=1).on(qubits[17]))
    circuit.append(cirq.H(qubits[17])**0)
    circuit.append(cirq.H(qubits[18])**1)
    circuit.append(cirq.PhaseDampingChannel(gamma=1).on(qubits[18]))
    circuit.append(cirq.H(qubits[18])**1)
    circuit.append(cirq.H(qubits[19])**1)
    circuit.append(cirq.PhaseDampingChannel(gamma=1).on(qubits[19]))
    circuit.append(cirq.H(qubits[19])**1)
    circuit.append(cirq.H(qubits[20])**0)
    circuit.append(cirq.PhaseDampingChannel(gamma=1).on(qubits[20]))
    circuit.append(cirq.H(qubits[20])**0)
    circuit.append(cirq.H(qubits[21])**0)
    circuit.append(cirq.PhaseDampingChannel(gamma=1).on(qubits[21]))
    circuit.append(cirq.H(qubits[21])**0)
    circuit.append(cirq.H(qubits[22])**0)
    circuit.append(cirq.PhaseDampingChannel(gamma=1).on(qubits[22]))
    circuit.append(cirq.H(qubits[22])**0)
    circuit.append(cirq.H(qubits[23])**0)
    circuit.append(cirq.PhaseDampingChannel(gamma=1).on(qubits[23]))
    circuit.append(cirq.H(qubits[23])**0)

    # Bob measures in his basis (H**basis then measure)
    circuit.append(cirq.H(qubits[0])**1)
    circuit.append(cirq.measure(qubits[0], key='c0'))
    circuit.append(cirq.H(qubits[1])**0)
    circuit.append(cirq.measure(qubits[1], key='c1'))
    circuit.append(cirq.H(qubits[2])**1)
    circuit.append(cirq.measure(qubits[2], key='c2'))
    circuit.append(cirq.H(qubits[3])**1)
    circuit.append(cirq.measure(qubits[3], key='c3'))
    circuit.append(cirq.H(qubits[4])**0)
    circuit.append(cirq.measure(qubits[4], key='c4'))
    circuit.append(cirq.H(qubits[5])**0)
    circuit.append(cirq.measure(qubits[5], key='c5'))
    circuit.append(cirq.H(qubits[6])**1)
    circuit.append(cirq.measure(qubits[6], key='c6'))
    circuit.append(cirq.H(qubits[7])**0)
    circuit.append(cirq.measure(qubits[7], key='c7'))
    circuit.append(cirq.H(qubits[8])**0)
    circuit.append(cirq.measure(qubits[8], key='c8'))
    circuit.append(cirq.H(qubits[9])**1)
    circuit.append(cirq.measure(qubits[9], key='c9'))
    circuit.append(cirq.H(qubits[10])**0)
    circuit.append(cirq.measure(qubits[10], key='c10'))
    circuit.append(cirq.H(qubits[11])**1)
    circuit.append(cirq.measure(qubits[11], key='c11'))
    circuit.append(cirq.H(qubits[12])**0)
    circuit.append(cirq.measure(qubits[12], key='c12'))
    circuit.append(cirq.H(qubits[13])**1)
    circuit.append(cirq.measure(qubits[13], key='c13'))
    circuit.append(cirq.H(qubits[14])**0)
    circuit.append(cirq.measure(qubits[14], key='c14'))
    circuit.append(cirq.H(qubits[15])**0)
    circuit.append(cirq.measure(qubits[15], key='c15'))
    circuit.append(cirq.H(qubits[16])**1)
    circuit.append(cirq.measure(qubits[16], key='c16'))
    circuit.append(cirq.H(qubits[17])**0)
    circuit.append(cirq.measure(qubits[17], key='c17'))
    circuit.append(cirq.H(qubits[18])**0)
    circuit.append(cirq.measure(qubits[18], key='c18'))
    circuit.append(cirq.H(qubits[19])**1)
    circuit.append(cirq.measure(qubits[19], key='c19'))
    circuit.append(cirq.H(qubits[20])**0)
    circuit.append(cirq.measure(qubits[20], key='c20'))
    circuit.append(cirq.H(qubits[21])**0)
    circuit.append(cirq.measure(qubits[21], key='c21'))
    circuit.append(cirq.H(qubits[22])**0)
    circuit.append(cirq.measure(qubits[22], key='c22'))
    circuit.append(cirq.H(qubits[23])**1)
    circuit.append(cirq.measure(qubits[23], key='c23'))
    return circuit
