gate mcphase_5367981136(_gate_p_0) _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6 {
  cp(pi/64) _gate_q_5, _gate_q_6;
  cx _gate_q_5, _gate_q_4;
  cp(-pi/64) _gate_q_4, _gate_q_6;
  cx _gate_q_5, _gate_q_4;
  cp(pi/64) _gate_q_4, _gate_q_6;
  cx _gate_q_4, _gate_q_3;
  cp(-pi/64) _gate_q_3, _gate_q_6;
  cx _gate_q_5, _gate_q_3;
  cp(pi/64) _gate_q_3, _gate_q_6;
  cx _gate_q_4, _gate_q_3;
  cp(-pi/64) _gate_q_3, _gate_q_6;
  cx _gate_q_5, _gate_q_3;
  cp(pi/64) _gate_q_3, _gate_q_6;
  cx _gate_q_3, _gate_q_2;
  cp(-pi/64) _gate_q_2, _gate_q_6;
  cx _gate_q_5, _gate_q_2;
  cp(pi/64) _gate_q_2, _gate_q_6;
  cx _gate_q_4, _gate_q_2;
  cp(-pi/64) _gate_q_2, _gate_q_6;
  cx _gate_q_5, _gate_q_2;
  cp(pi/64) _gate_q_2, _gate_q_6;
  cx _gate_q_3, _gate_q_2;
  cp(-pi/64) _gate_q_2, _gate_q_6;
  cx _gate_q_5, _gate_q_2;
  cp(pi/64) _gate_q_2, _gate_q_6;
  cx _gate_q_4, _gate_q_2;
  cp(-pi/64) _gate_q_2, _gate_q_6;
  cx _gate_q_5, _gate_q_2;
  cp(pi/64) _gate_q_2, _gate_q_6;
  cx _gate_q_2, _gate_q_1;
  cp(-pi/64) _gate_q_1, _gate_q_6;
  cx _gate_q_5, _gate_q_1;
  cp(pi/64) _gate_q_1, _gate_q_6;
  cx _gate_q_4, _gate_q_1;
  cp(-pi/64) _gate_q_1, _gate_q_6;
  cx _gate_q_5, _gate_q_1;
  cp(pi/64) _gate_q_1, _gate_q_6;
  cx _gate_q_3, _gate_q_1;
  cp(-pi/64) _gate_q_1, _gate_q_6;
  cx _gate_q_5, _gate_q_1;
  cp(pi/64) _gate_q_1, _gate_q_6;
  cx _gate_q_4, _gate_q_1;
  cp(-pi/64) _gate_q_1, _gate_q_6;
  cx _gate_q_5, _gate_q_1;
  cp(pi/64) _gate_q_1, _gate_q_6;
  cx _gate_q_2, _gate_q_1;
  cp(-pi/64) _gate_q_1, _gate_q_6;
  cx _gate_q_5, _gate_q_1;
  cp(pi/64) _gate_q_1, _gate_q_6;
  cx _gate_q_4, _gate_q_1;
  cp(-pi/64) _gate_q_1, _gate_q_6;
  cx _gate_q_5, _gate_q_1;
  cp(pi/64) _gate_q_1, _gate_q_6;
  cx _gate_q_3, _gate_q_1;
  cp(-pi/64) _gate_q_1, _gate_q_6;
  cx _gate_q_5, _gate_q_1;
  cp(pi/64) _gate_q_1, _gate_q_6;
  cx _gate_q_4, _gate_q_1;
  cp(-pi/64) _gate_q_1, _gate_q_6;
  cx _gate_q_5, _gate_q_1;
  cp(pi/64) _gate_q_1, _gate_q_6;
  cx _gate_q_1, _gate_q_0;
  cp(-pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_5, _gate_q_0;
  cp(pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_5, _gate_q_0;
  cp(pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_3, _gate_q_0;
  cp(-pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_5, _gate_q_0;
  cp(pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_5, _gate_q_0;
  cp(pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_2, _gate_q_0;
  cp(-pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_5, _gate_q_0;
  cp(pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_5, _gate_q_0;
  cp(pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_3, _gate_q_0;
  cp(-pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_5, _gate_q_0;
  cp(pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_5, _gate_q_0;
  cp(pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_1, _gate_q_0;
  cp(-pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_5, _gate_q_0;
  cp(pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_5, _gate_q_0;
  cp(pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_3, _gate_q_0;
  cp(-pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_5, _gate_q_0;
  cp(pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_5, _gate_q_0;
  cp(pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_2, _gate_q_0;
  cp(-pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_5, _gate_q_0;
  cp(pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_5, _gate_q_0;
  cp(pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_3, _gate_q_0;
  cp(-pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_5, _gate_q_0;
  cp(pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/64) _gate_q_0, _gate_q_6;
  cx _gate_q_5, _gate_q_0;
  cp(pi/64) _gate_q_0, _gate_q_6;
}
gate c7z _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7 {
  U(pi/2, 0, pi) _gate_q_7;
  cx _gate_q_7, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_7, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  U(pi/2, pi/4, -3*pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  p(-pi/4) _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  p(pi/4) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  U(pi/2, 0, 3*pi/4) _gate_q_4;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, -pi/4, 3*pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_7, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_7, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  p(-pi/4) _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  p(pi/4) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  U(pi/2, 0, 3*pi/4) _gate_q_4;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, 0, 3*pi/4) _gate_q_5;
  U(pi/4, pi/2, -pi/2) _gate_q_7;
  cx _gate_q_7, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  U(pi/2, pi/4, -3*pi/4) _gate_q_3;
  cx _gate_q_5, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_4, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_5, _gate_q_3;
  U(pi/2, -pi/4, 3*pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_3;
  cx _gate_q_5, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_4, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_5, _gate_q_3;
  U(pi/2, 0, 3*pi/4) _gate_q_3;
  U(pi/4, -pi/2, pi/2) _gate_q_7;
  cx _gate_q_7, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_7, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  U(pi/2, pi/4, -3*pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  p(-pi/4) _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  p(pi/4) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  U(pi/2, 0, 3*pi/4) _gate_q_4;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, -pi/4, 3*pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_7, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_7, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  p(-pi/4) _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  p(pi/4) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  U(pi/2, 0, 3*pi/4) _gate_q_4;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, 0, 3*pi/4) _gate_q_5;
  U(pi/4, pi/2, -pi/2) _gate_q_7;
  cx _gate_q_7, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  U(pi/2, pi/4, -3*pi/4) _gate_q_3;
  cx _gate_q_5, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_4, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_5, _gate_q_3;
  U(pi/2, -pi/4, 3*pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_3;
  cx _gate_q_5, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_4, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_5, _gate_q_3;
  U(pi/2, 0, 3*pi/4) _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_7;
  mcphase_5367981136(pi/2) _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6;
}
gate Oracle _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7 {
  x _gate_q_0;
  c7z _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7;
  x _gate_q_0;
}
gate cu1_5364565248(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
}
gate cu1_5364565824(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5364568992(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5364568512(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5364571824(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5364564048(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5364568704(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5364570000(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5364571872(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5364569616(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5364564912(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5364571584(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5364578784(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5364576864(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5364568560(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5364576240(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5364579840(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5364574320(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5364566880(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895754320(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5364579264(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5364568896(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895926368(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895926032(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895915808(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895925120(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895926752(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895916576(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895926224(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895916336(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895923632(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895923584(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895926320(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895913744(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895919600(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895914032(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895926080(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895923392(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895918352(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895917632(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895915904(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895919120(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895917152(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895915136(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895914176(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895927856(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895927424(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895913552(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895925312(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895926992(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895927280(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895915088(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895926800(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895916384(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895918016(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895917680(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895914704(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895919456(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895919744(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895927904(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895927088(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895916480(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5895916816(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate cu1_5364475920(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/128) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/128) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/128) _gate_q_1;
}
gate mcu1_5364570336(_gate_p_0) _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7 {
  cu1_5364565248(pi/64) _gate_q_6, _gate_q_7;
  cx _gate_q_6, _gate_q_5;
  cu1_5364565824(-pi/64) _gate_q_5, _gate_q_7;
  cx _gate_q_6, _gate_q_5;
  cu1_5364565248(pi/64) _gate_q_5, _gate_q_7;
  cx _gate_q_5, _gate_q_4;
  cu1_5364568992(-pi/64) _gate_q_4, _gate_q_7;
  cx _gate_q_6, _gate_q_4;
  cu1_5364565248(pi/64) _gate_q_4, _gate_q_7;
  cx _gate_q_5, _gate_q_4;
  cu1_5364568512(-pi/64) _gate_q_4, _gate_q_7;
  cx _gate_q_6, _gate_q_4;
  cu1_5364565248(pi/64) _gate_q_4, _gate_q_7;
  cx _gate_q_4, _gate_q_3;
  cu1_5364571824(-pi/64) _gate_q_3, _gate_q_7;
  cx _gate_q_6, _gate_q_3;
  cu1_5364565248(pi/64) _gate_q_3, _gate_q_7;
  cx _gate_q_5, _gate_q_3;
  cu1_5364564048(-pi/64) _gate_q_3, _gate_q_7;
  cx _gate_q_6, _gate_q_3;
  cu1_5364565248(pi/64) _gate_q_3, _gate_q_7;
  cx _gate_q_4, _gate_q_3;
  cu1_5364568704(-pi/64) _gate_q_3, _gate_q_7;
  cx _gate_q_6, _gate_q_3;
  cu1_5364565248(pi/64) _gate_q_3, _gate_q_7;
  cx _gate_q_5, _gate_q_3;
  cu1_5364570000(-pi/64) _gate_q_3, _gate_q_7;
  cx _gate_q_6, _gate_q_3;
  cu1_5364565248(pi/64) _gate_q_3, _gate_q_7;
  cx _gate_q_3, _gate_q_2;
  cu1_5364571872(-pi/64) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cu1_5364565248(pi/64) _gate_q_2, _gate_q_7;
  cx _gate_q_5, _gate_q_2;
  cu1_5364569616(-pi/64) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cu1_5364565248(pi/64) _gate_q_2, _gate_q_7;
  cx _gate_q_4, _gate_q_2;
  cu1_5364564912(-pi/64) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cu1_5364565248(pi/64) _gate_q_2, _gate_q_7;
  cx _gate_q_5, _gate_q_2;
  cu1_5364571584(-pi/64) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cu1_5364565248(pi/64) _gate_q_2, _gate_q_7;
  cx _gate_q_3, _gate_q_2;
  cu1_5364578784(-pi/64) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cu1_5364565248(pi/64) _gate_q_2, _gate_q_7;
  cx _gate_q_5, _gate_q_2;
  cu1_5364576864(-pi/64) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cu1_5364565248(pi/64) _gate_q_2, _gate_q_7;
  cx _gate_q_4, _gate_q_2;
  cu1_5364568560(-pi/64) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cu1_5364565248(pi/64) _gate_q_2, _gate_q_7;
  cx _gate_q_5, _gate_q_2;
  cu1_5364576240(-pi/64) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cu1_5364565248(pi/64) _gate_q_2, _gate_q_7;
  cx _gate_q_2, _gate_q_1;
  cu1_5364579840(-pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cu1_5364565248(pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cu1_5364574320(-pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cu1_5364565248(pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_4, _gate_q_1;
  cu1_5364566880(-pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cu1_5364565248(pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cu1_5895754320(-pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cu1_5364565248(pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_3, _gate_q_1;
  cu1_5364579264(-pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cu1_5364565248(pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cu1_5364568896(-pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cu1_5364565248(pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_4, _gate_q_1;
  cu1_5895926368(-pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cu1_5364565248(pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cu1_5895926032(-pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cu1_5364565248(pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_2, _gate_q_1;
  cu1_5895915808(-pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cu1_5364565248(pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cu1_5895925120(-pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cu1_5364565248(pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_4, _gate_q_1;
  cu1_5895926752(-pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cu1_5364565248(pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cu1_5895916576(-pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cu1_5364565248(pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_3, _gate_q_1;
  cu1_5895926224(-pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cu1_5364565248(pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cu1_5895916336(-pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cu1_5364565248(pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_4, _gate_q_1;
  cu1_5895923632(-pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cu1_5364565248(pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cu1_5895923584(-pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cu1_5364565248(pi/64) _gate_q_1, _gate_q_7;
  cx _gate_q_1, _gate_q_0;
  cu1_5895926320(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cu1_5895913744(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cu1_5895919600(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cu1_5895914032(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_3, _gate_q_0;
  cu1_5895926080(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cu1_5895923392(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cu1_5895918352(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cu1_5895917632(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_2, _gate_q_0;
  cu1_5895915904(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cu1_5895919120(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cu1_5895917152(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cu1_5895915136(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_3, _gate_q_0;
  cu1_5895914176(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cu1_5895927856(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cu1_5895927424(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cu1_5895913552(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_1, _gate_q_0;
  cu1_5895925312(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cu1_5895926992(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cu1_5895927280(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cu1_5895915088(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_3, _gate_q_0;
  cu1_5895926800(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cu1_5895916384(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cu1_5895918016(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cu1_5895917680(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_2, _gate_q_0;
  cu1_5895914704(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cu1_5895919456(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cu1_5895919744(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cu1_5895927904(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_3, _gate_q_0;
  cu1_5895927088(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cu1_5895916480(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cu1_5895916816(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cu1_5364475920(-pi/64) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cu1_5364565248(pi/64) _gate_q_0, _gate_q_7;
}
gate mcx _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7 {
  h _gate_q_7;
  mcu1_5364570336(pi) _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7;
  h _gate_q_7;
}